# Unit tests: state-dependent speciation and extinction (R/core_mod_sse*.R).

test_that('guane_bisse_data codes the explicit state 0 and validates inputs', {
 d <- guane_test_data()
 z <- guane_bisse_data(d$tree, d$traits, 'species', 'habitat_binary', 'terrestrial')
 expect_equal(z$mapping$State, c('terrestrial', 'aquatic'))
 expect_equal(unname(z$states), as.integer(d$traits$habitat_binary[match(d$tree$tip.label, d$traits$species)] != 'terrestrial'))
 expect_equal(sum(z$mapping$Count), length(d$tree$tip.label))
 expect_error(guane_bisse_data(d$tree, d$traits, 'species', 'habitat_binary', 'marine'), 'explicit state 0')
 expect_error(guane_bisse_data(d$tree, d$traits, 'species', 'locomotion_3state', 'walking'), 'two observed states')
 expect_error(guane_bisse_data(d$tree, d$traits[-1, ], 'species', 'habitat_binary', 'terrestrial'), 'Match tree and trait taxa')
 expect_error(guane_bisse_data(d$tree, d$traits, 'species', 'species', 'Sp01'), 'taxon column and a binary trait')
 small <- ape::keep.tip(d$tree, d$tree$tip.label[1:3])
 expect_error(guane_bisse_data(small, d$traits, 'species', 'habitat_binary', 'terrestrial'), 'at least four tips')
})

test_that('BiSSE constraint templates tie or fix the documented parameters', {
 d <- guane_test_data()
 tab <- guane_bisse_parameters(d$tree)
 expect_equal(tab$Parameter, guane_bisse_names())
 tid <- guane_bisse_constraint(tab, 'Trait-independent diversification')
 expect_setequal(tid$free, c('lambda0', 'mu0', 'q01', 'q10'))
 noext <- guane_bisse_constraint(tab, 'No extinction')
 expect_equal(noext$table$Fixed[3:4], c(0, 0))
 expect_false(any(c('mu0', 'mu1') %in% noext$free))
 expect_equal(guane_sse_expand(c(lambda0 = 1, mu0 = .2, q01 = .1, q10 = .3)[tid$free], tid),
  c(lambda0 = 1, lambda1 = 1, mu0 = .2, mu1 = .2, q01 = .1, q10 = .3))
 expect_error(guane_bisse_constraint(tab, 'Everything'), 'Select supported BiSSE models.')
 expect_error(guane_bisse_parameters(d$tree, 'a,b\n1,2'), 'Invalid BiSSE parameter table.')
 txt <- paste(c('Parameter,Group,Fixed,Start,Lower,Upper', paste0(tab$Parameter, ',', tab$Group, ',,', -1, ',0,10')), collapse = '\n')
 expect_error(guane_bisse_parameters(d$tree, txt), 'finite nonnegative bounds')
})

test_that('guane_bisse_fit fits one cheap BiSSE model on habitat_binary', {
 d <- guane_test_data()
 r <- guane_bisse_fit(d$tree, d$traits, 'species', 'habitat_binary', 'terrestrial', models = 'Trait-independent diversification', starts = 1, slices = FALSE)
 expect_equal(r$comparison$Model, 'Trait-independent diversification')
 expect_true(r$comparison$Converged)
 expect_true(is.finite(r$comparison$LogLik))
 p <- r$fits[[1]]$par
 expect_equal(unname(p['lambda0']), unname(p['lambda1']))
 expect_equal(unname(p['mu0']), unname(p['mu1']))
 expect_true(all(p >= 0))
 # A single candidate never receives an AIC weight.
 expect_true(is.na(r$comparison$Weight))
 expect_true(any(grepl('exploratory', r$warnings)))
 # Refit reproduces the same likelihood (deterministic starts, no RNG).
 again <- guane_bisse_fit(d$tree, d$traits, 'species', 'habitat_binary', 'terrestrial', models = 'Trait-independent diversification', starts = 1, slices = FALSE)
 expect_equal(again$comparison$LogLik, r$comparison$LogLik)
})

test_that('guane_bisse_fit validates its settings', {
 d <- guane_test_data()
 f <- function(...) guane_bisse_fit(d$tree, d$traits, 'species', 'habitat_binary', 'terrestrial', ...)
 expect_error(f(models = 'Weird'), 'Select supported BiSSE models.')
 expect_error(f(sampling = 1), 'Both state sampling fractions')
 expect_error(f(sampling = c(0, 1)), 'Both state sampling fractions')
 expect_error(f(root_p = c(.2, .2)), 'Root probabilities must be nonnegative and sum to one.')
 expect_error(f(root = 'MAX'), 'Invalid BiSSE likelihood settings.')
 expect_error(f(starts = 9), 'Invalid BiSSE optimizer settings.')
 expect_error(f(backend = 'rk4'), 'Invalid BiSSE integration settings.')
 expect_error(guane_bisse_settings(type = 'pie'), 'Invalid BiSSE graph settings.')
})

test_that('guane_musse_fit fits a constrained MuSSE model on locomotion_3state', {
 d <- guane_test_data()
 r <- guane_musse_fit(d$tree, d$traits, 'species', 'locomotion_3state', models = 'Equal diversification and transitions', starts = 1, slices = FALSE)
 expect_equal(r$k, 3L)
 expect_equal(r$mapping$State, c('flying', 'swimming', 'walking'))
 expect_true(r$comparison$Converged)
 p <- r$fits[[1]]$par
 expect_equal(length(unique(p[c('lambda1', 'lambda2', 'lambda3')])), 1L)
 expect_equal(length(unique(p[grepl('^q', names(p))])), 1L)
 expect_equal(r$comparison$Parameters, 3)
})

test_that('MuSSE helpers validate states, tables and roots', {
 d <- guane_test_data()
 expect_equal(guane_musse_names(2), c('lambda1', 'lambda2', 'mu1', 'mu2', 'q12', 'q21'))
 expect_error(guane_musse_names(9), 'two to eight observed states')
 st <- guane_musse_state_table(d$traits, 'locomotion_3state')
 expect_equal(st$RootWeight, rep(1 / 3, 3))
 expect_error(guane_musse_state_table(d$traits, 'locomotion_3state', 'State,Sampling,RootWeight\nflying,1,1'), 'each observed state exactly once')
 expect_error(guane_musse_state_table(d$traits, 'locomotion_3state', 'State,Sampling,RootWeight\nflying,0,.3\nswimming,1,.3\nwalking,1,.4'), 'sampling fractions')
 expect_error(guane_musse_state_table(d$traits, 'locomotion_3state', 'State,Sampling,RootWeight\nflying,1,.5\nswimming,1,.5\nwalking,1,.5'), 'sum to one')
 expect_error(guane_musse_fit(d$tree, d$traits, 'species', 'locomotion_3state', models = 'Equal transitions', root = 'EQUI', starts = 1), 'equilibrium roots are unavailable')
 expect_error(guane_musse_fit(d$tree, d$traits, 'species', 'locomotion_3state', models = 'None'), 'Select supported MuSSE models.')
 sym <- guane_musse_constraint(guane_musse_parameters(d$tree, 3), 'Symmetric transitions', 3)
 expect_equal(sym$table$Group[sym$table$Parameter == 'q21'], 'q12')
})

test_that('QuaSSE helpers validate rate functions, data, grid and parameter tables', {
 d <- guane_test_data()
 expect_equal(guane_quasse_function('Constant')(1:3, 2), c(2, 2, 2))
 expect_error(guane_quasse_function('Linear'), 'Select supported QuaSSE rate functions.')
 expect_error(guane_quasse_data(d$tree, d$traits, 'species', 'habitat_binary'), 'finite, nonconstant continuous observations')
 expect_error(guane_quasse_data(d$tree, d$traits, 'species', 'body_mass', error = 0), 'standard errors must be positive')
 expect_error(guane_quasse_data(d$tree, d$traits, 'species', 'body_mass', error_column = 'nope'), 'valid measurement-error column')
 expect_error(guane_quasse_data(d$tree, d$traits[-1, ], 'species', 'body_mass'), 'Match tree and trait taxa')
 q <- guane_quasse_data(d$tree, d$traits, 'species', 'body_mass')
 expect_equal(names(q$states), q$tree$tip.label)
 expect_error(guane_quasse_control(q, nx = 100), 'Invalid QuaSSE integration settings.')
 expect_error(guane_quasse_control(q, xmid = 1e6), 'grid must contain all observed trait values')
 ctl <- guane_quasse_control(q)
 expect_equal(ctl$xmid, mean(range(q$states)))
 tab <- guane_quasse_parameters(q, 'Sigmoid', 'Constant')
 expect_equal(tab$Parameter, c('l.y0', 'l.y1', 'l.xmid', 'l.r', 'm.c', 'drift', 'diffusion'))
 expect_equal(tab$Fixed[tab$Parameter == 'drift'], 0)
 expect_error(guane_quasse_parameters(q, text = 'x,y\n1,2'), 'Invalid QuaSSE parameter table.')
 expect_error(guane_quasse_likelihood(q, 'Constant', 'Constant', ctl, sampling = 2), 'Invalid QuaSSE sampling or root settings.')
 expect_error(guane_quasse_fit(d$tree, d$traits, 'species', 'body_mass', starts = 0), 'Invalid QuaSSE optimizer settings.')
})

test_that('guane_quasse_fit fits a constant-rate model on log body mass', {
 # About 5 s; kept in the gate (well under the 20 s budget).
 d <- guane_test_data(); d$traits$log_mass <- log(d$traits$body_mass)
 r <- guane_quasse_fit(d$tree, d$traits, 'species', 'log_mass', error = .1, nx = 256, r = 2, starts = 1, maxit = 200, baseline = FALSE, verify = FALSE)
 expect_equal(r$comparison$Model, 'Selected')
 expect_true(r$comparison$Converged)
 expect_true(is.finite(r$comparison$LogLik))
 expect_true(r$fits$Selected$par['diffusion'] > 0)
})

test_that('hidden-state helpers validate model specifications and settings', {
 skip_if_not_installed('hisse')
 d <- guane_test_data()
 cid <- guane_hidden_spec('CID-2')
 expect_equal(cid$classes, 2)
 expect_equal(cid$turnover, c(1, 1, 2, 2))
 expect_equal(cid$states, c('0A', '1A', '0B', '1B'))
 b <- guane_hidden_spec('BiSSE (HiSSE backend)')
 expect_equal(b$classes, 1); expect_equal(b$turnover, 1:2)
 expect_equal(guane_hidden_spec('HiSSE', eps_mode = 'Zero extinction')$eps, rep(0, 4))
 expect_error(guane_hidden_spec('Mystery'), 'Invalid hidden-state model settings.')
 expect_error(guane_hidden_spec('HiSSE', eps_mode = 'None'), 'Invalid hidden-state model settings.')
 expect_error(guane_hidden_spec('Custom', turnover_text = '1,3,1,1'), 'consecutive parameter indices')
 f <- function(...) guane_hidden_fit(d$tree, d$traits, 'species', 'habitat_binary', 'terrestrial', ...)
 expect_error(f(models = 'Mystery'), 'Select supported hidden-state models.')
 expect_error(f(sampling = c(1, 0)), 'Invalid hidden-state sampling or root settings.')
 expect_error(f(root_type = 'flat'), 'Invalid hidden-state sampling or root settings.')
 expect_error(f(starts = 0), 'Invalid hidden-state optimizer settings.')
 expect_error(f(turnover_start = 200), 'Starts must be positive and below finite upper bounds.')
 expect_error(guane_hidden_fit(d$tree, d$traits, 'species', 'habitat_binary', 'marine'), 'hidden-state analysis requires two observed states')
})
