server_mod_signal_signal <- function(input, output, session, data) {
 state<-data$state; attempt<-data$attempt; result<-shiny::reactiveVal(NULL)
 selected_trait<-shiny::reactive(if(is.null(input$signal_trait) || !nzchar(input$signal_trait)) data$trait() else input$signal_trait)
 shiny::observeEvent(list(state$traits,data$taxon()),{
  cols<-setdiff(names(state$traits)[vapply(state$traits,is.numeric,logical(1))],data$taxon())
  selected<-if(length(input$signal_trait)==1 && input$signal_trait %in% cols) input$signal_trait else if(length(data$trait())==1 && data$trait() %in% cols) data$trait() else head(cols,1)
  shiny::updateSelectInput(session,'signal_trait',choices=cols,selected=selected)
 },ignoreNULL=FALSE)
 shiny::observeEvent(list(state$tree,state$traits,data$taxon(),selected_trait(),data$seed(),input$nsim), {signal_task$discard();result(NULL)},ignoreInit=TRUE)
    signal_task<-guane_task(function(r,warnings)attempt({
      for(w in warnings) warning(w,call.=FALSE)
      result(r)
      state$activity<-'Signal analysis completed. Results correspond to the current inputs.';bslib::nav_select('analysis',selected='signal',session=session)
    }),function(msg){state$activity<-msg;shiny::showNotification(msg,type='error')},function(msg)state$activity<-msg)
    observeEvent(input$run,{result(NULL);attempt({
      req(data$seed(),input$nsim)
      if(input$nsim<99 || input$nsim>9999 || input$nsim != floor(input$nsim)) stop('Choose 99\u20139999 integer randomizations.')
      if(data$seed()<0 || data$seed()>2147483647 || data$seed() != floor(data$seed())) stop('Choose a nonnegative integer seed up to 2147483647.')
      signal_task$run(guane_signal,list(state$tree,state$traits,data$taxon(),selected_trait(),data$seed(),input$nsim))
    })})
    output$results <- renderTable({validate(need(!is.null(result()),'Run an analysis on validated data to see results.'));transform(result(), Estimate = formatC(Estimate, digits=5, format='fg'), P_value = format.pval(P_value, digits=4, eps=1e-6))},digits=5)
    plot_type<-reactive(if(is.null(input$signal_graph)) 'tree' else input$signal_graph)
    palette<-reactive(if(is.null(input$signal_palette)) 'Guane' else input$signal_palette)
    font<-reactive(if(is.null(input$signal_font)) .8 else input$signal_font)
    height<-reactive({h<-input$signal_height;if(is.null(h) || !is.finite(h)) 7 else max(4,min(20,h))})
    draw<-function(type=plot_type()) guane_signal_plot(result(),type,palette(),font(),data$lang())
    output$signal_plot<-renderPlot({req(result());draw()},height=function() height()*72,res=110)
    output$signal_null<-renderPlot({req(result());draw('null')},res=110)
    output$signal_metadata<-renderUI({req(result());s<-attr(result(),'snapshot');tagList(
      p(strong(s$trait)),p(span('Seed:'),s$seed,' | ',span('K test draws:'),s$nsim,' | ',span('Randomized draws:'),length(attr(result(),'randomized_K'))))})
    output$signal_pdf<-downloadHandler('guane-signal.pdf',function(file){req(result());pdf(file,width=9,height=height());on.exit(dev.off());draw()})
    output$signal_csv<-downloadHandler('guane-signal.csv',function(file){req(result());guane_write_csv(result(),file,row.names=FALSE)})
    code <- reactive({req(result());paste(guane_signal_script(result(),plot_type(),palette(),font(),data$lang(),height()),collapse='\n')})
    output$code <- renderText(code())
    output$script <- downloadHandler('guane-analysis.R',function(file) writeLines(code(),file))
    output$tree_download <- downloadHandler('guane-tree.nwk',function(file){req(state$tree);ape::write.tree(state$tree,file)})
  list(result=result, code=code)
}
