server_mod_asr_poly <- function(input,output,session,data) {
 result<-shiny::reactiveVal(NULL);status<-shiny::reactiveVal('Choose a polymorphic trait and run reconstruction.')
 shiny::observeEvent(list(data$state$traits,data$taxon()),{
  t<-data$state$traits;cols<-setdiff(names(t),data$taxon())
  cols<-cols[vapply(t[cols],function(v)is.character(v)||is.factor(v),logical(1))]
  preferred<-cols[vapply(t[cols],function(v)any(grepl('+',as.character(v),fixed=TRUE)),logical(1))]
  shiny::updateSelectInput(session,'poly_trait',choices=cols,selected=if(length(input$poly_trait)==1 && input$poly_trait%in%cols)input$poly_trait else head(c(preferred,cols),1))
 },ignoreNULL=FALSE)
 order_settings<-shiny::reactive(list(ordered=isTRUE(input$poly_ordered),state_order=if(isTRUE(input$poly_ordered))strsplit(if(is.null(input$poly_order))'' else input$poly_order,'\n',fixed=TRUE)[[1]] else NULL,max_poly=if(isTRUE(input$poly_ordered))input$poly_max_poly else NULL))
 preview<-shiny::reactive(tryCatch({d<-do.call(guane_poly_data,c(list(tree=data$state$tree,traits=data$state$traits,taxon=data$taxon(),trait=input$poly_trait),order_settings()));guane_poly_matrix(d$states,input$poly_model)},error=identity))
 output$poly_preview_status<-shiny::renderText({p<-preview();guane_text(if(inherits(p,'error'))conditionMessage(p) else 'Constraints are valid. Review allowed transitions before running.',data$lang())})
 output$poly_preview<-shiny::renderTable({p<-preview();shiny::req(!inherits(p,'error'));p},rownames=TRUE)
 advanced<-server_asr_mk_advanced(input,output,session,'poly',shiny::reactive({d<-do.call(guane_poly_data,c(list(tree=data$state$tree,traits=data$state$traits,taxon=data$taxon(),trait=input$poly_trait),order_settings()));list(data=d,index=guane_poly_matrix(d$states,input$poly_model))}),lang=data$lang)
 bayes_options<-server_asr_bayes_controls(input,output,session,'poly',shiny::reactive({m<-preview();if(inherits(m,'error'))stop(m);m}),result,status)
 shiny::observeEvent(list(data$state$tree,data$state$traits,data$taxon(),input$poly_trait,input$poly_framework,input$poly_model,order_settings(),if(identical(input$poly_framework,'Bayes'))bayes_options() else list(input$poly_compare,advanced$maximum(),advanced$options(),if(identical(input$poly_framework,'simmap'))list(input$poly_nsim,input$poly_seed))),{
  result(NULL);status('Inputs changed. Run polymorphic reconstruction to update results.')
 },ignoreInit=TRUE)
 shiny::observeEvent(input$poly_run,{
  result(NULL)
  tryCatch({
   if(!input$poly_framework %in% c('ML','simmap','Bayes'))stop('This framework is planned. Choose ML or fixed-rate stochastic mapping.')
   r<-shiny::withProgress(message=guane_text('Run polymorphic reconstruction',data$lang()),value=.1,{
    if(identical(input$poly_framework,'Bayes'))do.call(guane_asr_poly_bayes,c(list(tree=data$state$tree,traits=data$state$traits,taxon=data$taxon(),trait=input$poly_trait,model=input$poly_model),order_settings(),bayes_options())) else do.call(guane_asr_poly,c(list(tree=data$state$tree,traits=data$state$traits,taxon=data$taxon(),trait=input$poly_trait,model=input$poly_model,compare=isTRUE(input$poly_compare),max_rate=advanced$maximum(),advanced=advanced$options()),order_settings()))})
   if(identical(input$poly_framework,'simmap')) {
    r<-shiny::withProgress(message=guane_text('Simulating conditional histories',data$lang()),value=.1,guane_asr_map(r,input$poly_nsim,input$poly_seed))
    shiny::updateNumericInput(session,'poly_history',value=1,min=1,max=r$mapping$nsim)
   }
   if(!is.null(r$bayes))shiny::updateNumericInput(session,'poly_history',min=1,max=r$mapping$nsim,value=1)
   result(r);status(if(!is.null(r$bayes))'Bayesian Mk completed. Inspect rate and node diagnostics before interpretation.' else if(is.null(r$mapping))'Polymorphic reconstruction completed. Review coding, constraints and diagnostics.' else 'Stochastic mapping completed. Review simulation precision and fitted-rate warnings.')
   if(!is.null(r$bayes))data$record('Bayesian Mk rate sampling completed.') else if(!is.null(r$mapping))data$record('Conditional stochastic mapping completed.')
   data$record('Polymorphic reconstruction completed. Combination coding is recorded in the analysis audit; source data are unchanged.')
  },error=function(e){status(conditionMessage(e));data$record(paste('Polymorphic Mk:',conditionMessage(e)))})
 })
 shiny::observeEvent(list(input$poly_framework,input$poly_reconstruction),{
  shiny::updateActionButton(session,'poly_run',label=if(identical(input$poly_framework,'Bayes'))'Run Bayesian Mk reconstruction' else if(identical(input$poly_framework,'simmap'))'Run stochastic mapping' else 'Run polymorphic reconstruction')
  choices<-c('Node probability tree'='tree','Selected node'='node','Transition-rate diagram'='rates','Marginal state probabilities'='probabilities','Model comparison'='comparison','Optimizer starts'='starts')
  if(identical(input$poly_reconstruction,'joint'))choices<-c(choices,'Joint ancestral assignments'='joint')
  if(identical(input$poly_framework,'simmap'))choices<-c('Conditional stochastic history'='history','Selected-state density map'='density','Selected transition distribution'='transition','Sampled node frequencies'='frequencies','Transition counts'='changes','State occupancy'='times','Monte Carlo agreement'='mc',choices)
  if(identical(input$poly_framework,'Bayes'))choices<-c('Posterior node probabilities'='tree','Selected node'='node','Posterior mean Q'='rates','Marginal state probabilities'='probabilities','Posterior stochastic history'='history','Selected-state density map'='density','Selected transition distribution'='transition','Transition counts'='changes','State occupancy'='times','MCMC trace'='trace','Posterior density'='posterior_density','Posterior rate intervals'='rate_intervals')
  shiny::updateSelectInput(session,'poly_graph',choices=choices,selected=if(identical(input$poly_framework,'simmap'))'history' else 'tree')
 },ignoreNULL=FALSE)
 output$poly_status<-shiny::renderText(guane_text(status(),data$lang()))
 appearance<-server_asr_graphics(input,output,session,'poly',result,data$lang)
 settings<-shiny::reactive(list(type=if(is.null(input$poly_graph))'tree' else input$poly_graph,palette=if(is.null(input$poly_palette))'Guane' else input$poly_palette,labels=isTRUE(input$poly_labels),node_labels=isTRUE(input$poly_nodes),label_size=if(is.null(input$poly_label_size)).7 else input$poly_label_size,pie_size=if(is.null(input$poly_pie_size)).6 else input$poly_pie_size,lang=data$lang(),history=if(is.null(input$poly_history))1 else input$poly_history,appearance=appearance(),parameter=if(is.null(input$poly_bayes_parameter))'q1' else input$poly_bayes_parameter))
 density_summary<-shiny::reactive({shiny::req(result()$mapping,input$poly_focus_state);guane_asr_density(result(),input$poly_focus_state,if(is.null(input$poly_resolution))100 else input$poly_resolution)})
 plot_result<-shiny::reactive({r<-result();shiny::req(r);if(identical(input$poly_graph,'density'))r$display_density<-density_summary();r})
 draw<-function()do.call(guane_asr_poly_plot,c(list(result=plot_result()),settings()))
 output$poly_diagnostics<-shiny::renderPlot({server_asr_plot(function(){shiny::req(result(),is.null(result()$bayes));s<-settings();s$type<-'comparison';do.call(guane_asr_poly_plot,c(list(result=plot_result()),s))},data$lang())},width=function()appearance()$width*96,height=function()appearance()$height*96,res=96)
 output$poly_interpretation<-shiny::renderText({shiny::req(result());r<-result();paste(sum(apply(r$probabilities,1,max)>=.9),'/',nrow(r$probabilities),guane_text('nodes have a most-supported state with probability at least 0.90. This is conditional support, not certainty.',data$lang()))})
 output$poly_plot<-shiny::renderPlot({server_asr_plot(function(){shiny::req(result());draw()},data$lang())},width=function()appearance()$width*96,height=function()appearance()$height*96,res=96)
 translate_headers<-function(t){names(t)<-vapply(names(t),guane_text,character(1),lang=data$lang());t}
 output$poly_probabilities<-shiny::renderTable({shiny::req(result());p<-result()$probabilities;t<-data.frame(Node=rownames(p),p,check.names=FALSE);names(t)[1]<-guane_text('Node',data$lang());t},digits=5)
 output$poly_joint<-shiny::renderTable({shiny::req(result()$joint);j<-result()$joint;data.frame(Node=names(j$states),State=unname(j$states))})
 output$poly_joint_info<-shiny::renderText({shiny::req(result()$joint);paste(guane_text('Joint log likelihood conditional on fitted Q; AIC uses the marginal likelihood.',data$lang()),signif(result()$joint$logLik,7))})
 output$poly_joint_csv<-shiny::downloadHandler('guane-poly-joint.csv',function(file){shiny::req(result()$joint);j<-result()$joint;utils::write.csv(data.frame(Node=names(j$states),State=unname(j$states)),file,row.names=FALSE)})
 output$poly_results_rds<-shiny::downloadHandler('guane-poly-analysis.rds',function(file){shiny::req(result());saveRDS(result(),file)})
 output$poly_q<-shiny::renderTable({shiny::req(result());result()$Q},rownames=TRUE,digits=6)
 output$poly_comparison<-shiny::renderTable({shiny::req(result(),is.null(result()$bayes));t<-result()$comparison;t$Status<-vapply(t$Status,guane_text,character(1),lang=data$lang());t$Message<-vapply(strsplit(t$Message,'\n',fixed=TRUE),function(x)paste(vapply(x,guane_text,character(1),lang=data$lang()),collapse='; '),character(1));translate_headers(t)},digits=5)
 output$poly_attempts<-shiny::renderTable({shiny::req(result(),is.null(result()$bayes));translate_headers(result()$attempts)},digits=5)
 output$poly_metadata<-shiny::renderText({shiny::req(result());r<-result();if(!is.null(r$bayes))return(paste(r$trait,'| Mk |',r$model,'| Bayesian | n =',length(r$x),'| make.simmap(Q="mcmc") |',r$bayes$chains,'chains |',r$mapping$nsim,'draws |',guane_text(if(r$ordered)'Ordered polymorphism' else 'Unordered polymorphism',data$lang()),if(r$ordered)paste(r$state_order,collapse=' → ')));paste(r$trait,'| Mk |',r$model,'| ML | n =',length(r$x),'| logLik =',signif(r$logLik,6),'| phytools::fitMk + ancr |',guane_text(if(r$ordered)'Ordered polymorphism' else 'Unordered polymorphism',data$lang()),if(r$ordered)paste(r$state_order,collapse=' → '),if(r$ordered)paste('|',guane_text('Maximum polymorphism',data$lang()),r$max_poly))})
 output$poly_warnings<-shiny::renderText({shiny::req(result());w<-c(result()$warnings,result()$mapping$warnings);if(!length(w))w<-'No fitting warnings reported. Inspect diagnostics before interpretation.';paste(vapply(w,guane_text,character(1),lang=data$lang()),collapse='\n')})
 code<-shiny::reactive({shiny::req(result());do.call(guane_asr_poly_script,c(list(result=plot_result()),settings()))})
 output$poly_code<-shiny::renderText(paste(if(is.null(result())){if(identical(input$poly_framework,'Bayes'))c('# guane_asr_poly_bayes: full coexistence state space and gain/loss constraints; effective controls follow.',capture.output(dput(c(order_settings(),bayes_options())))) else advanced$preview()} else code(),collapse='\n'))
 output$poly_script<-shiny::downloadHandler('guane-polymorphic.R',function(file)writeLines(code(),file))
 output$poly_png<-shiny::downloadHandler('guane-poly.png',function(file){shiny::req(result());g<-appearance();grDevices::png(file,width=g$width,height=g$height,units='in',res=g$dpi);on.exit(grDevices::dev.off());draw()})
 output$poly_view_rds<-shiny::downloadHandler('guane-poly-view.rds',function(file){shiny::req(result());saveRDS(list(result=result(),plot_settings=settings()),file)})
 output$poly_pdf<-shiny::downloadHandler('guane-polymorphic.pdf',function(file){shiny::req(result());grDevices::pdf(file,width=appearance()$width,height=appearance()$height);on.exit(grDevices::dev.off());draw()})
 output$poly_diagnostic_pdf<-shiny::downloadHandler('guane-polymorphic-comparison.pdf',function(file){shiny::req(result());grDevices::pdf(file,width=appearance()$width,height=appearance()$height);on.exit(grDevices::dev.off());s<-settings();s$type<-'comparison';do.call(guane_asr_poly_plot,c(list(result=plot_result()),s))})
 output$poly_diagnostic_script<-shiny::downloadHandler('guane-polymorphic-comparison.R',function(file){shiny::req(result());s<-settings();s$type<-'comparison';writeLines(do.call(guane_asr_poly_script,c(list(result=plot_result()),s)),file)})
 output$poly_csv<-shiny::downloadHandler('guane-polymorphic-probabilities.csv',function(file){shiny::req(result());utils::write.csv(result()$probabilities,file)})
 output$poly_q_csv<-shiny::downloadHandler('guane-polymorphic-rates.csv',function(file){shiny::req(result());utils::write.csv(result()$Q,file)})
 output$poly_comparison_csv<-shiny::downloadHandler('guane-polymorphic-comparison.csv',function(file){shiny::req(result(),is.null(result()$bayes));utils::write.csv(result()$comparison,file,row.names=FALSE)})
 output$poly_attempts_csv<-shiny::downloadHandler('guane-polymorphic-optimizer.csv',function(file){shiny::req(result(),is.null(result()$bayes));utils::write.csv(result()$attempts,file,row.names=FALSE)})
 output$poly_coding<-shiny::renderTable({shiny::req(result());translate_headers(result()$coding)})
 output$poly_constraints<-shiny::renderTable({shiny::req(result());result()$index},rownames=TRUE)
 output$poly_coding_csv<-shiny::downloadHandler('guane-polymorphic-coding.csv',function(file){shiny::req(result());utils::write.csv(result()$coding,file,row.names=FALSE)})
 output$poly_density_csv<-shiny::downloadHandler('guane-density-segments.csv',function(file){shiny::req(result()$mapping);utils::write.csv(density_summary()$table,file,row.names=FALSE)})
 mapping<-shiny::reactive({shiny::req(result(),result()$mapping);result()$mapping})
 output$poly_mapping_info<-shiny::renderText({m<-mapping();paste(guane_text('Saved histories',data$lang()),m$nsim,'|',guane_text('Mapping seed',data$lang()),m$seed)})
 output$poly_transitions<-shiny::renderTable(translate_headers(mapping()$transition_summary),digits=4)
 output$poly_occupancy<-shiny::renderTable(translate_headers(mapping()$time_summary),digits=4)
 output$poly_mc_table<-shiny::renderTable(translate_headers(mapping()$node_summary),digits=4)
 output$poly_mc_plot<-shiny::renderPlot({server_asr_plot(function(){mapping();s<-settings();s$type<-'mc';do.call(guane_asr_poly_plot,c(list(result=plot_result()),s))},data$lang())},width=function()appearance()$width*96,height=function()appearance()$height*96,res=96)
 output$poly_mc_pdf<-shiny::downloadHandler('guane-polymorphic-mapping-diagnostic.pdf',function(file){mapping();grDevices::pdf(file,width=appearance()$width,height=appearance()$height);on.exit(grDevices::dev.off());s<-settings();s$type<-'mc';do.call(guane_asr_poly_plot,c(list(result=plot_result()),s))})
 output$poly_mc_script<-shiny::downloadHandler('guane-polymorphic-mapping-diagnostic.R',function(file){mapping();s<-settings();s$type<-'mc';writeLines(do.call(guane_asr_poly_script,c(list(result=plot_result()),s)),file)})
 output$poly_transitions_csv<-shiny::downloadHandler('guane-polymorphic-mapping-transitions.csv',function(file)utils::write.csv(mapping()$transition_summary,file,row.names=FALSE))
 output$poly_occupancy_csv<-shiny::downloadHandler('guane-polymorphic-mapping-occupancy.csv',function(file)utils::write.csv(mapping()$time_summary,file,row.names=FALSE))
 output$poly_frequency_csv<-shiny::downloadHandler('guane-polymorphic-mapping-node-frequencies.csv',function(file)utils::write.csv(mapping()$node_summary,file,row.names=FALSE))
 output$poly_maps_rds<-shiny::downloadHandler('guane-polymorphic-mapping-results.rds',function(file){mapping();saveRDS(result(),file)})
 server_asr_bayes_outputs(input,output,session,'poly',result,settings,appearance,data,guane_asr_poly_plot,guane_asr_poly_script,translate_headers)
 list(result=result,code=code)
}
