server_mod_asr_discrete <- function(input,output,session,data) {
 result<-shiny::reactiveVal(NULL);status<-shiny::reactiveVal('Choose a discrete trait and run Mk reconstruction.')
 shiny::observeEvent(list(data$state$traits,data$taxon()),{
  t<-data$state$traits;cols<-setdiff(names(t),data$taxon())
  # Offer categorical or integer-coded states, not continuous columns.
  cols<-cols[vapply(t[cols],function(v){z<-unique(v[!is.na(v)]);length(z)>=2 && length(z)<=10 && (!is.numeric(v)||all(is.finite(z)&z==floor(z)))},logical(1))]
  shiny::updateSelectInput(session,'mk_trait',choices=cols,selected=if(length(input$mk_trait)==1 && input$mk_trait%in%cols)input$mk_trait else head(cols,1))
 },ignoreNULL=FALSE)
 states<-shiny::reactive({shiny::req(input$mk_trait %in% names(data$state$traits));sort(unique(as.character(data$state$traits[[input$mk_trait]])),method='radix')})
 output$mk_states<-shiny::renderText(paste(guane_text('State order',data$lang()),paste(states(),collapse=' | '),sep=': '))
 shiny::observeEvent(input$mk_fill,{
  tryCatch({m<-guane_mk_matrix(states(),input$mk_template);shiny::updateTextAreaInput(session,'mk_custom',value=paste(apply(m,1,paste,collapse=', '),collapse='\n'))},error=function(e)status(conditionMessage(e)))
 })
 # A custom matrix belongs to a particular trait/state order; clear on analytical data changes.
 shiny::observeEvent(list(data$state$traits,input$mk_trait),{
  shiny::updateTextAreaInput(session,'mk_custom',value='')
 },ignoreInit=TRUE)
 custom<-shiny::reactive(tryCatch(guane_mk_matrix(states(),'Custom',input$mk_custom),error=identity))
 output$mk_matrix<-shiny::renderTable({shiny::req(identical(input$mk_model,'Custom'));m<-custom();shiny::req(!inherits(m,'error'));m},rownames=TRUE)
 output$mk_matrix_status<-shiny::renderText({shiny::req(identical(input$mk_model,'Custom'));m<-custom();guane_text(if(inherits(m,'error'))conditionMessage(m) else 'Custom constraints are valid.',data$lang())})
 advanced<-server_asr_mk_advanced(input,output,session,'mk',shiny::reactive({d<-guane_mk_data(data$state$tree,data$state$traits,data$taxon(),input$mk_trait);list(data=d,index=guane_mk_matrix(d$states,input$mk_model,input$mk_custom))}),lang=data$lang)
 bayes_options<-server_asr_bayes_controls(input,output,session,'mk',shiny::reactive(guane_mk_matrix(states(),input$mk_model,input$mk_custom)),result,status)
 shiny::observeEvent(list(data$state$tree,data$state$traits,data$taxon(),input$mk_trait,input$mk_framework,input$mk_model,if(identical(input$mk_model,'Custom'))input$mk_custom,if(identical(input$mk_framework,'Bayes'))bayes_options() else list(input$mk_compare,advanced$maximum(),advanced$options(),if(identical(input$mk_framework,'simmap'))list(input$mk_nsim,input$mk_seed))),{
  result(NULL);status('Inputs changed. Run Mk reconstruction to update results.')
 },ignoreInit=TRUE)
 shiny::observeEvent(input$mk_run,{
  result(NULL)
  tryCatch({
   if(!input$mk_framework %in% c('ML','simmap','Bayes'))stop('This framework is planned. Choose ML or fixed-rate stochastic mapping.')
   r<-shiny::withProgress(message=guane_text('Run Mk reconstruction',data$lang()),value=.1,{if(identical(input$mk_framework,'Bayes'))do.call(guane_asr_mk_bayes,c(list(tree=data$state$tree,traits=data$state$traits,taxon=data$taxon(),trait=input$mk_trait,model=input$mk_model,custom=input$mk_custom),bayes_options())) else guane_asr_mk(data$state$tree,data$state$traits,data$taxon(),input$mk_trait,input$mk_model,input$mk_custom,isTRUE(input$mk_compare),advanced$maximum(),advanced$options())})
   if(identical(input$mk_framework,'simmap')) {
    r<-shiny::withProgress(message=guane_text('Simulating conditional histories',data$lang()),value=.1,{guane_asr_map(r,input$mk_nsim,input$mk_seed)})
    shiny::updateNumericInput(session,'mk_history',min=1,max=r$mapping$nsim,value=1)
   }
   if(!is.null(r$bayes))shiny::updateNumericInput(session,'mk_history',min=1,max=r$mapping$nsim,value=1)
   result(r);status(if(!is.null(r$bayes))'Bayesian Mk completed. Inspect rate and node diagnostics before interpretation.' else if(is.null(r$mapping))'Mk reconstruction completed. Review optimizer diagnostics and model assumptions.' else 'Stochastic mapping completed. Review simulation precision and fitted-rate warnings.');data$record(if(!is.null(r$bayes))'Bayesian Mk rate sampling completed.' else if(is.null(r$mapping))'Discrete Mk reconstruction completed.' else 'Conditional stochastic mapping completed.')
  },error=function(e){status(conditionMessage(e));data$record(paste('Mk:',conditionMessage(e)))})
 })
 shiny::observeEvent(list(input$mk_framework,input$mk_reconstruction),{
  shiny::updateActionButton(session,'mk_run',label=if(identical(input$mk_framework,'Bayes'))'Run Bayesian Mk reconstruction' else if(identical(input$mk_framework,'simmap'))'Run stochastic mapping' else 'Run Mk reconstruction')
  choices<-c('Node probability tree'='tree','Selected node'='node','Transition-rate diagram'='rates','Marginal state probabilities'='probabilities','Model comparison'='comparison','Optimizer starts'='starts')
  if(identical(input$mk_reconstruction,'joint'))choices<-c(choices,'Joint ancestral assignments'='joint')
  if(identical(input$mk_framework,'simmap'))choices<-c('Conditional stochastic history'='history','Selected-state density map'='density','Selected transition distribution'='transition','Sampled node frequencies'='frequencies','Transition counts'='changes','State occupancy'='times','Monte Carlo agreement'='mc',choices)
  if(identical(input$mk_framework,'Bayes'))choices<-c('Posterior node probabilities'='tree','Selected node'='node','Posterior mean Q'='rates','Marginal state probabilities'='probabilities','Posterior stochastic history'='history','Selected-state density map'='density','Selected transition distribution'='transition','Transition counts'='changes','State occupancy'='times','MCMC trace'='trace','Posterior density'='posterior_density','Posterior rate intervals'='rate_intervals')
  shiny::updateSelectInput(session,'mk_graph',choices=choices,selected=if(identical(input$mk_framework,'simmap'))'history' else 'tree')
 },ignoreNULL=FALSE)
 output$mk_status<-shiny::renderText(guane_text(status(),data$lang()))
 appearance<-server_asr_graphics(input,output,session,'mk',result,data$lang)
 settings<-shiny::reactive(list(type=if(is.null(input$mk_graph))'tree' else input$mk_graph,palette=if(is.null(input$mk_palette))'Guane' else input$mk_palette,labels=isTRUE(input$mk_labels),node_labels=isTRUE(input$mk_nodes),label_size=if(is.null(input$mk_label_size)).7 else input$mk_label_size,pie_size=if(is.null(input$mk_pie_size)).6 else input$mk_pie_size,lang=data$lang(),history=if(is.null(input$mk_history))1 else input$mk_history,appearance=appearance(),parameter=if(is.null(input$mk_bayes_parameter))'q1' else input$mk_bayes_parameter))
 density_summary<-shiny::reactive({shiny::req(result()$mapping,input$mk_focus_state);guane_asr_density(result(),input$mk_focus_state,if(is.null(input$mk_resolution))100 else input$mk_resolution)})
 plot_result<-shiny::reactive({r<-result();shiny::req(r);if(identical(input$mk_graph,'density'))r$display_density<-density_summary();r})
 draw<-function()do.call(guane_asr_mk_plot,c(list(result=plot_result()),settings()))
 output$mk_diagnostics<-shiny::renderPlot({server_asr_plot(function(){shiny::req(result(),is.null(result()$bayes));s<-settings();s$type<-'comparison';do.call(guane_asr_mk_plot,c(list(result=plot_result()),s))},data$lang())},width=function()appearance()$width*96,height=function()appearance()$height*96,res=96)
 output$mk_interpretation<-shiny::renderText({shiny::req(result());r<-result();paste(sum(apply(r$probabilities,1,max)>=.9),'/',nrow(r$probabilities),guane_text('nodes have a most-supported state with probability at least 0.90. This is conditional support, not certainty.',data$lang()))})
 output$mk_plot<-shiny::renderPlot({server_asr_plot(function(){shiny::req(result());draw()},data$lang())},width=function()appearance()$width*96,height=function()appearance()$height*96,res=96)
 translate_headers<-function(t){names(t)<-vapply(names(t),guane_text,character(1),lang=data$lang());t}
 output$mk_probabilities<-shiny::renderTable({shiny::req(result());p<-result()$probabilities;t<-data.frame(Node=rownames(p),p,check.names=FALSE);names(t)[1]<-guane_text('Node',data$lang());t},digits=5)
 output$mk_joint<-shiny::renderTable({shiny::req(result()$joint);j<-result()$joint;data.frame(Node=names(j$states),State=unname(j$states))})
 output$mk_joint_info<-shiny::renderText({shiny::req(result()$joint);paste(guane_text('Joint log likelihood conditional on fitted Q; AIC uses the marginal likelihood.',data$lang()),signif(result()$joint$logLik,7))})
 output$mk_joint_csv<-shiny::downloadHandler('guane-mk-joint.csv',function(file){shiny::req(result()$joint);j<-result()$joint;utils::write.csv(data.frame(Node=names(j$states),State=unname(j$states)),file,row.names=FALSE)})
 output$mk_results_rds<-shiny::downloadHandler('guane-mk-analysis.rds',function(file){shiny::req(result());saveRDS(result(),file)})
 output$mk_q<-shiny::renderTable({shiny::req(result());result()$Q},rownames=TRUE,digits=6)
 output$mk_comparison<-shiny::renderTable({shiny::req(result(),is.null(result()$bayes));t<-result()$comparison;t$Status<-vapply(t$Status,guane_text,character(1),lang=data$lang());t$Message<-vapply(strsplit(t$Message,'\n',fixed=TRUE),function(x)paste(vapply(x,guane_text,character(1),lang=data$lang()),collapse='; '),character(1));translate_headers(t)},digits=5)
 output$mk_attempts<-shiny::renderTable({shiny::req(result(),is.null(result()$bayes));translate_headers(result()$attempts)},digits=5)
 output$mk_metadata<-shiny::renderText({shiny::req(result());r<-result();if(!is.null(r$bayes))return(paste(r$trait,'| Mk |',r$model,'| Bayesian | n =',length(r$x),'| make.simmap(Q=\"mcmc\") |',r$bayes$chains,'chains |',r$mapping$nsim,'draws'));paste(r$trait,'| Mk |',r$model,'| ML | n =',length(r$x),'| logLik =',signif(r$logLik,6),if(is.null(r$mapping))'| phytools::fitMk + ancr' else '| fixed-Q make.simmap')})
 output$mk_warnings<-shiny::renderText({shiny::req(result());w<-c(result()$warnings,result()$mapping$warnings);if(!length(w))w<-'No fitting warnings reported. Inspect diagnostics before interpretation.';paste(vapply(w,guane_text,character(1),lang=data$lang()),collapse='\n')})
 code<-shiny::reactive({shiny::req(result());do.call(guane_asr_mk_script,c(list(result=plot_result()),settings()))})
 output$mk_code<-shiny::renderText(paste(if(is.null(result())){if(identical(input$mk_framework,'Bayes'))c('# guane_asr_mk_bayes: validated Mk model and fixed root weights; effective controls follow.',capture.output(dput(bayes_options()))) else advanced$preview()} else code(),collapse='\n'))
 output$mk_script<-shiny::downloadHandler('guane-discrete-mk.R',function(file)writeLines(code(),file))
 output$mk_png<-shiny::downloadHandler('guane-mk.png',function(file){shiny::req(result());g<-appearance();grDevices::png(file,width=g$width,height=g$height,units='in',res=g$dpi);on.exit(grDevices::dev.off());draw()})
 output$mk_view_rds<-shiny::downloadHandler('guane-mk-view.rds',function(file){shiny::req(result());saveRDS(list(result=result(),plot_settings=settings()),file)})
 output$mk_pdf<-shiny::downloadHandler('guane-discrete-mk.pdf',function(file){shiny::req(result());grDevices::pdf(file,width=appearance()$width,height=appearance()$height);on.exit(grDevices::dev.off());draw()})
 output$mk_diagnostic_pdf<-shiny::downloadHandler('guane-mk-comparison.pdf',function(file){shiny::req(result());grDevices::pdf(file,width=appearance()$width,height=appearance()$height);on.exit(grDevices::dev.off());s<-settings();s$type<-'comparison';do.call(guane_asr_mk_plot,c(list(result=plot_result()),s))})
 output$mk_diagnostic_script<-shiny::downloadHandler('guane-mk-comparison.R',function(file){shiny::req(result());s<-settings();s$type<-'comparison';writeLines(do.call(guane_asr_mk_script,c(list(result=plot_result()),s)),file)})
 output$mk_csv<-shiny::downloadHandler('guane-mk-probabilities.csv',function(file){shiny::req(result());utils::write.csv(result()$probabilities,file)})
 output$mk_q_csv<-shiny::downloadHandler('guane-mk-rates.csv',function(file){shiny::req(result());utils::write.csv(result()$Q,file)})
 output$mk_comparison_csv<-shiny::downloadHandler('guane-mk-comparison.csv',function(file){shiny::req(result());utils::write.csv(result()$comparison,file,row.names=FALSE)})
 output$mk_attempts_csv<-shiny::downloadHandler('guane-mk-optimizer.csv',function(file){shiny::req(result());utils::write.csv(result()$attempts,file,row.names=FALSE)})
 output$mk_density_csv<-shiny::downloadHandler('guane-density-segments.csv',function(file){shiny::req(result()$mapping);utils::write.csv(density_summary()$table,file,row.names=FALSE)})
 mapping<-shiny::reactive({shiny::req(result(),result()$mapping);result()$mapping})
 output$mk_mapping_info<-shiny::renderText({m<-mapping();paste(guane_text('Saved histories',data$lang()),m$nsim,'|',guane_text('Mapping seed',data$lang()),m$seed)})
 output$mk_transitions<-shiny::renderTable(translate_headers(mapping()$transition_summary),digits=4)
 output$mk_occupancy<-shiny::renderTable(translate_headers(mapping()$time_summary),digits=4)
 output$mk_mc_table<-shiny::renderTable(translate_headers(mapping()$node_summary),digits=4)
 output$mk_mc_plot<-shiny::renderPlot({server_asr_plot(function(){mapping();s<-settings();s$type<-'mc';do.call(guane_asr_mk_plot,c(list(result=plot_result()),s))},data$lang())},width=function()appearance()$width*96,height=function()appearance()$height*96,res=96)
 output$mk_mc_pdf<-shiny::downloadHandler('guane-mapping-diagnostic.pdf',function(file){mapping();grDevices::pdf(file,width=appearance()$width,height=appearance()$height);on.exit(grDevices::dev.off());s<-settings();s$type<-'mc';do.call(guane_asr_mk_plot,c(list(result=plot_result()),s))})
 output$mk_mc_script<-shiny::downloadHandler('guane-mapping-diagnostic.R',function(file){mapping();s<-settings();s$type<-'mc';writeLines(do.call(guane_asr_mk_script,c(list(result=plot_result()),s)),file)})
 output$mk_transitions_csv<-shiny::downloadHandler('guane-mapping-transitions.csv',function(file)utils::write.csv(mapping()$transition_summary,file,row.names=FALSE))
 output$mk_occupancy_csv<-shiny::downloadHandler('guane-mapping-occupancy.csv',function(file)utils::write.csv(mapping()$time_summary,file,row.names=FALSE))
 output$mk_frequency_csv<-shiny::downloadHandler('guane-mapping-node-frequencies.csv',function(file)utils::write.csv(mapping()$node_summary,file,row.names=FALSE))
 output$mk_maps_rds<-shiny::downloadHandler('guane-mapping-results.rds',function(file){mapping();saveRDS(result(),file)})
 server_asr_bayes_outputs(input,output,session,'mk',result,settings,appearance,data,guane_asr_mk_plot,guane_asr_mk_script,translate_headers)
 list(result=result,code=code)
}
