ui_mod_sse_hidden <- function(id) {
 ns<-shiny::NS(id)
 ui_mod_analysis_base(id,'hidden','Hidden-state and null models',controls=shiny::tagList(
  shiny::tags$details(open=TRUE,shiny::tags$summary('Model and data settings'),
   shiny::selectInput(ns('hidden_trait'),'Binary trait',choices=NULL),shiny::selectInput(ns('hidden_state0'),'State 0',choices=NULL),
   shiny::checkboxGroupInput(ns('hidden_models'),'Models',guane_hidden_models(),selected=c('HiSSE','CID-2','CID-4')),
   shiny::selectInput(ns('hidden_eps_mode'),'Extinction-fraction constraints',c('Shared','By diversification class','Zero extinction')),
   shiny::numericInput(ns('hidden_sampling0'),'Sampling fraction: state 0',1,min=.001,max=1),shiny::numericInput(ns('hidden_sampling1'),'Sampling fraction: state 1',1,min=.001,max=1),
   shiny::checkboxInput(ns('hidden_survival'),'Condition on crown survival and root split',TRUE),
   shiny::selectInput(ns('hidden_root_type'),'Root conditioning',c('madfitz','herr_als')),
   shiny::selectInput(ns('hidden_root_mode'),'Root weights',c('Likelihood','Given')),
   shiny::numericInput(ns('hidden_root0'),'Given probability of observed state 0',.5,min=0,max=1),
   shiny::p('Given root weights divide each observed-state probability equally among hidden classes. All candidates share observed coding, sampling and root settings.')),
  shiny::tags$details(shiny::tags$summary('Custom model constraints'),
   shiny::selectInput(ns('hidden_custom_classes'),'Hidden classes in Custom',c(2,4),selected=2),
   shiny::textInput(ns('hidden_turnover_text'),'Turnover indices (comma-separated)',''),shiny::textInput(ns('hidden_eps_text'),'Extinction-fraction indices (comma-separated)',''),
   shiny::actionButton(ns('hidden_fill'),'Fill custom constraints'),shiny::textAreaInput(ns('hidden_transition_text'),'Transition indices (CSV, no header)','',rows=8),
   shiny::p('Custom only: order 0A,1A,0B,1B, then 0C,1C,0D,1D for four classes. Consecutive positive indices share parameters. Zero fixes extinction fractions or transitions to zero. Simultaneous observed and hidden changes are forbidden.'),
   shiny::p('CID models tie diversification across observed states within each hidden class. Hidden classes are not observed or assigned to tips.')),
  shiny::tags$details(shiny::tags$summary('Advanced fitting controls'),
   shiny::checkboxInput(ns('hidden_verify'),'Verify with an independent optimizer',TRUE),shiny::numericInput(ns('hidden_maxeval'),'Maximum optimizer evaluations',100000,min=10,max=1000000),
   shiny::numericInput(ns('hidden_starts'),'Optimizer starts',2,min=1,max=8),shiny::numericInput(ns('hidden_seed'),'Seed',999,min=0,max=2147480000),
   shiny::checkboxInput(ns('hidden_sann'),'Use simulated annealing',FALSE),shiny::numericInput(ns('hidden_sann_its'),'Annealing objective calls',1000,min=10,max=100000),
   shiny::numericInput(ns('hidden_tolerance'),'Relative optimizer tolerance',1e-8,min=1e-12,max=.001),
   shiny::numericInput(ns('hidden_turnover_start'),'Starting turnover',.5,min=.000001),shiny::numericInput(ns('hidden_eps_start'),'Starting extinction fraction',.2,min=.000001),shiny::numericInput(ns('hidden_transition_start'),'Starting transition rate',.1,min=.000001),
   shiny::numericInput(ns('hidden_turnover_upper'),'Turnover upper bound',100,min=.000001),shiny::numericInput(ns('hidden_eps_upper'),'Extinction-fraction upper bound',3,min=.000001),shiny::numericInput(ns('hidden_transition_upper'),'Transition upper bound',100,min=.000001),shiny::numericInput(ns('hidden_ode_eps'),'ODE rejection threshold',0,min=0,max=.001),
   shiny::p('Bounded subplex retains its log-rate lower bound of -20. Evaluation limits are editable. Long runs are synchronous.')),
  shiny::actionButton(ns('hidden_run'),'Run hidden-state models'),shiny::textOutput(ns('hidden_status')),
  shiny::p('Optimizer status is retained. Weights require converged repeatable interior fits and agreement with an independent optimizer.')),
 results=shiny::tagList(
  shiny::fluidRow(shiny::column(9,shiny::div(class='guane-asr-figure',shiny::plotOutput(ns('hidden_plot'),height='auto'))),shiny::column(3,
   shiny::h4('Graph controls'),shiny::selectInput(ns('hidden_graph'),'Graph',c('Rate estimates'='rates','Observed tip states'='tree','Transition rates'='transitions','Model comparison'='comparison','Optimizer starts'='starts','Independent optimizer verification'='verification')),
   shiny::selectInput(ns('hidden_plot_model'),'Model',choices='HiSSE'),
   shiny::selectInput(ns('hidden_palette'),'Palette',c('Guane','Legacy','Grayscale')),shiny::checkboxInput(ns('hidden_labels'),'Show tip labels',TRUE),
   shiny::numericInput(ns('hidden_font'),'Label size',.7,min=.2,max=2),shiny::numericInput(ns('hidden_width'),'Figure width (inches)',10,min=5,max=24),shiny::numericInput(ns('hidden_height'),'Figure height (inches)',7,min=4,max=24),
   shiny::downloadButton(ns('hidden_pdf'),'Download graph PDF'),shiny::downloadButton(ns('hidden_png'),'Download graph PNG'),shiny::downloadButton(ns('hidden_script'),'Download graph R code'))),
  shiny::textOutput(ns('hidden_metadata')),shiny::tableOutput(ns('hidden_estimates')),shiny::downloadButton(ns('hidden_csv'),'Download estimates CSV'),
  shiny::tableOutput(ns('hidden_comparison')),shiny::downloadButton(ns('hidden_comparison_csv'),'Download model comparison CSV'),
  shiny::p('Turnover = lambda + mu; extinction fraction = mu / lambda. Hidden-state labels can exchange between fits. Rates use branch-length units.'),
  shiny::textOutput(ns('hidden_interpretation')),shiny::downloadButton(ns('hidden_rds'),'Download graph settings and result RDS')),
 diagnostics=shiny::tagList(shiny::verbatimTextOutput(ns('hidden_warnings')),shiny::tableOutput(ns('hidden_attempts')),
  shiny::downloadButton(ns('hidden_attempts_csv'),'Download optimizer diagnostics CSV'),
  shiny::h4('Effective parameter constraints'),shiny::verbatimTextOutput(ns('hidden_constraints')),
  shiny::p('Compare only models refitted in this card with the same data and likelihood settings. Do not combine AIC values from other cards.')),
 mirror=shiny::verbatimTextOutput(ns('hidden_code')))
}
