ui_mod_div_diversity <- function(id) {
 ns<-shiny::NS(id)
 ui_mod_analysis_base(id,'diversity','Diversity-dependent models',
 controls=shiny::tagList(
  shiny::tags$details(open=TRUE,shiny::tags$summary('Model and data settings'),
   shiny::checkboxGroupInput(ns('dd_models'),'ddmodel',c('1: linear lambda'='1','1.3: linear lambda (K prime)'='1.3','2: exponential lambda'='2','3: linear mu'='3','4: exponential mu'='4','5: linear lambda + mu'='5'),selected='1'),
   shiny::numericInput(ns('dd_missing'),'Missing extant species',0,min=0,step=1),
   shiny::selectInput(ns('dd_cond'),'cond',c('0: age'='0','1: age + survival'='1','2: age + extant count'='2','3: extant count'='3'),selected='1'),
   shiny::selectInput(ns('dd_btorph'),'btorph',c('0: branching times'='0','1: phylogeny'='1'),selected='1'),
   shiny::p('Crown analysis (soc = 2). Missing species are a count, not a sampling fraction. Supplied stems are excluded.'),
   shiny::p('K has a model-specific meaning. Model 1.3 uses diversity at zero speciation; models 1 and 2 use diversity at equal speciation and extinction.')),
  shiny::tags$details(shiny::tags$summary('Advanced fitting controls'),
   shiny::textInput(ns('dd_starts'),'lambda, mu, K, r','3,0.2,40,1'),
   shiny::checkboxGroupInput(ns('dd_free'),'Estimated parameters',c('lambda','mu','K','r'),selected=c('lambda','mu','K')),
   shiny::p('Unchecked parameters use the supplied fixed values. r applies only to model 5. DDD does not expose arbitrary parameter bounds.'),
   shiny::textInput(ns('dd_res'),'res (blank = backend default)',''),
   shiny::textInput(ns('dd_tol'),'tol','0.001,0.0001,0.000001'),shiny::textInput(ns('dd_tolint'),'tolint','1e-10,1e-8'),
   shiny::numericInput(ns('dd_maxiter'),'maxiter',1000,min=1),shiny::numericInput(ns('dd_cycles'),'num_cycles',1,min=1),
   shiny::selectInput(ns('dd_optimizer'),'optimmethod',c('simplex','subplex')),
   shiny::selectInput(ns('dd_method'),'methode',c('analytical','odeint::runge_kutta_cash_karp54')),
   shiny::numericInput(ns('dd_threshold'),'probs_threshold',0,min=0,max=1),
   shiny::checkboxInput(ns('dd_change'),'changeloglikifnoconv',FALSE),shiny::checkboxInput(ns('dd_verbose'),'verbose',FALSE)),
  shiny::actionButton(ns('dd_run'),'Run diversity-dependent models'),shiny::textOutput(ns('dd_status')),
  shiny::tags$details(shiny::tags$summary('Uncertainty and diagnostics'),
   shiny::numericInput(ns('dd_factor'),'Resolution multiplier',2,min=1.1),
   shiny::actionButton(ns('dd_diagnose'),'Run numerical diagnostics'),
   shiny::p('Reevaluate saved estimates with larger res and tighter integration tolerances. This is a numerical check, not an uncertainty interval.'),
   shiny::selectInput(ns('dd_unc_model'),'Uncertainty model',choices=c('1','1.3','2','3','4','5')),
   shiny::checkboxInput(ns('dd_profiles'),'Calculate profile likelihoods',TRUE),
   shiny::selectInput(ns('dd_unc_parameter'),'Profile parameter',c('lambda','mu','K','r')),
   shiny::numericInput(ns('dd_lower'),'Profile lower search limit',.1,min=0),shiny::numericInput(ns('dd_upper'),'Profile upper search limit',10,min=0),
   shiny::numericInput(ns('dd_points'),'Profile grid points',21,min=5,max=101),shiny::numericInput(ns('dd_level'),'Reference level',.95,min=.5,max=.99),
   shiny::checkboxInput(ns('dd_robustness'),'Refit from multiple starts',TRUE),shiny::textInput(ns('dd_start_factors'),'Start multipliers','0.5,2'),
   shiny::checkboxInput(ns('dd_bootstrap'),'Parametric bootstrap',FALSE),shiny::numericInput(ns('dd_nsim'),'Bootstrap replicates',20,min=20,max=500),shiny::numericInput(ns('dd_bootseed'),'Simulation seed',999,min=0),
   shiny::numericInput(ns('dd_seconds'),'Seconds per bootstrap replicate',30,min=1),
   shiny::actionButton(ns('dd_unc_run'),'Run uncertainty and robustness'),
   shiny::p('Profiles use finite search limits and approximate chi-square reference levels. Bootstrap requires complete sampling and cond = 1; crown age is fixed, simulated tip counts vary. Intervals exclude tree and model-selection uncertainty.'))),
 results=shiny::tagList(shiny::fluidRow(
  shiny::column(9,shiny::div(class='guane-asr-figure',shiny::plotOutput(ns('dd_plot'),height='auto'))),
  shiny::column(3,shiny::h4('Graph controls'),
   shiny::selectInput(ns('dd_graph'),'Graph',c('Rate versus diversity'='rates','Model comparison'='comparison','Observed reconstructed lineages'='ltt','Numerical stability'='diagnostics','Profile likelihood'='profile','Robustness refits'='robustness','Bootstrap distribution'='bootstrap')),
   shiny::selectInput(ns('dd_model'),'ddmodel',choices='1'),shiny::numericInput(ns('dd_maxdiv'),'Maximum displayed diversity',100,min=2,max=10000),
   shiny::selectInput(ns('dd_parameter'),'Bootstrap parameter',c('lambda','mu','K','r')),
   shiny::selectInput(ns('dd_palette'),'Palette',c('Guane','Grayscale')),
   shiny::downloadButton(ns('dd_pdf'),'Download graph PDF'),shiny::downloadButton(ns('dd_png'),'Download graph PNG'),shiny::downloadButton(ns('dd_script'),'Download graph R code'))),
  shiny::p('Rate curves describe dependence on diversity. The LTT shows observed surviving lineages, not reconstructed total historical diversity.'),
  shiny::p('AIC compares selected candidates in this card only. It conditions on the tree and missing-species count. Uncertainty is conditional and approximate.'),
  shiny::p('Run numerical diagnostics before interpreting AIC. Failed stability checks suppress ranking weights.'),
  shiny::tableOutput(ns('dd_comparison')),shiny::tableOutput(ns('dd_estimates')),
  shiny::downloadButton(ns('dd_csv'),'Download estimates CSV'),shiny::downloadButton(ns('dd_comparison_csv'),'Download model comparison CSV'),shiny::downloadButton(ns('dd_rds'),'Download graph settings and result RDS')),
 diagnostics=shiny::tagList(shiny::verbatimTextOutput(ns('dd_unc_messages')),
 shiny::tableOutput(ns('dd_interval')),shiny::tableOutput(ns('dd_robustness_table')),shiny::tableOutput(ns('dd_bootstrap_intervals')),shiny::tableOutput(ns('dd_bootstrap_table')),
 shiny::downloadButton(ns('dd_profile_csv'),'Download profile curves CSV'),shiny::downloadButton(ns('dd_interval_csv'),'Download profile intervals CSV'),shiny::downloadButton(ns('dd_robustness_csv'),'Download robustness CSV'),shiny::downloadButton(ns('dd_bootstrap_csv'),'Download bootstrap refits CSV'),shiny::downloadButton(ns('dd_bootstrap_intervals_csv'),'Download bootstrap intervals CSV'),shiny::tableOutput(ns('dd_diagnostics')),shiny::verbatimTextOutput(ns('dd_log')),shiny::downloadButton(ns('dd_diagnostics_csv'),'Download diagnostics CSV')),
 mirror=shiny::verbatimTextOutput(ns('dd_code')))
}
