ui_mod_sse_bisse <- function(id) {
 ns<-shiny::NS(id)
 ui_mod_analysis_base(id,'bisse','BiSSE',
 controls=shiny::tagList(
  shiny::tags$details(open=TRUE,shiny::tags$summary('Model and data settings'),
   shiny::selectInput(ns('bisse_trait'),'Binary trait',choices=NULL),
   shiny::selectInput(ns('bisse_state0'),'Observed value coded as state 0',choices=NULL),
   shiny::p('The other observed value is coded as state 1. Resolve taxon mismatches in Data.'),
   shiny::checkboxGroupInput(ns('bisse_models'),'Models',choices=guane_bisse_models(),selected=c('Full','Trait-independent diversification')),
   shiny::numericInput(ns('bisse_rho0'),'Sampling fraction for state 0',1,min=.000001,max=1,step=.05),
   shiny::numericInput(ns('bisse_rho1'),'Sampling fraction for state 1',1,min=.000001,max=1,step=.05),
   shiny::p('Sampling assumes random inclusion within each state; fractions are treated as known.'),
   shiny::checkboxInput(ns('bisse_survival'),'Condition on crown survival and root split',TRUE),
   shiny::selectInput(ns('bisse_root'),'Root treatment',c('Observed (ROOT.OBS)'='OBS','Equal (ROOT.FLAT)'='FLAT','Equilibrium (ROOT.EQUI)'='EQUI','Given (ROOT.GIVEN)'='GIVEN')),
   shiny::p('ROOT.OBS uses likelihood-based root weights, not tip frequencies. Root treatment is shared by all candidates.'),
   shiny::conditionalPanel(sprintf("input['%s'] == 'GIVEN'",ns('bisse_root')),shiny::numericInput(ns('bisse_root0'),'Root probability for state 0',.5,min=0,max=1,step=.05))),
  shiny::tags$details(shiny::tags$summary('Advanced fitting controls'),
   shiny::checkboxInput(ns('bisse_verify'),'Verify with an independent optimizer',TRUE),
   shiny::actionButton(ns('bisse_fill'),'Fill parameter table'),
   shiny::textAreaInput(ns('bisse_parameters'),'BiSSE parameter table (CSV)','',rows=9),
   shiny::p('Columns: Parameter,Group,Fixed,Start,Lower,Upper. Use lambda0, lambda1, mu0, mu1, q01, q10. Blank uses tree-scaled defaults. Group and Fixed apply only to Custom; preset models use their own constraints. Shared Group values tie rates; a numeric Fixed value fixes the whole group.'),
   shiny::selectInput(ns('bisse_optimizer'),'Optimizer',c('nlminb','L-BFGS-B')),
   shiny::numericInput(ns('bisse_starts'),'Optimizer starts',3,min=1,max=8,step=1),
   shiny::numericInput(ns('bisse_maxit'),'Maximum iterations',500,min=10,max=5000,step=100),
   shiny::selectInput(ns('bisse_backend'),'ODE backend',c('gslode','deSolve'),selected=guane_bisse_backend()),
   shiny::numericInput(ns('bisse_tol'),'ODE tolerance',1e-8,min=1e-12,max=1e-4),
   shiny::numericInput(ns('bisse_eps'),'Integration retry threshold (eps)',0,min=0,max=.001),
   shiny::checkboxInput(ns('bisse_slices'),'Save likelihood slices',TRUE)),
  shiny::tags$details(shiny::tags$summary('Profile uncertainty'),
   shiny::p('Choose the model and parameter in Graph controls, then set the profile search bounds.'),
   shiny::numericInput(ns('bisse_profile_lower'),'Profile lower search bound',0,min=0),shiny::numericInput(ns('bisse_profile_upper'),'Profile upper search bound',1,min=0),
   shiny::numericInput(ns('bisse_profile_points'),'Profile grid points',15,min=5,max=101),shiny::numericInput(ns('bisse_profile_level'),'Profile confidence level',.95,min=.51,max=.999),
   shiny::actionButton(ns('bisse_profile_run'),'Run profile uncertainty')),
  shiny::actionButton(ns('bisse_run'),'Run BiSSE'),shiny::textOutput(ns('bisse_status')),
  shiny::p('BiSSE support is exploratory. Use the Hidden-state and null models card to refit compatible binary candidates.')),
 results=shiny::tagList(
  shiny::fluidRow(shiny::column(9,shiny::div(class='guane-asr-figure',shiny::plotOutput(ns('bisse_plot'),height='auto'))),
   shiny::column(3,shiny::h4('Graph controls'),
    shiny::selectInput(ns('bisse_graph'),'Graph',c('Rate estimates'='rates','Observed tip states'='tree','Transition rates'='transitions','Model comparison'='comparison','Optimizer starts'='starts','Independent optimizer verification'='verification','Likelihood slice'='slice','Profile likelihood'='profile')),
    shiny::selectInput(ns('bisse_plot_model'),'Model',choices='Full'),
    shiny::selectInput(ns('bisse_plot_parameter'),'Parameter',choices=guane_bisse_names()),
    shiny::selectInput(ns('bisse_palette'),'Palette',c('Guane','Legacy','Grayscale')),
    shiny::checkboxInput(ns('bisse_labels'),'Show tip labels',TRUE),
    shiny::numericInput(ns('bisse_font'),'Label size',.7,min=.2,max=2,step=.1),
    shiny::numericInput(ns('bisse_width'),'Figure width (inches)',10,min=5,max=24),
    shiny::numericInput(ns('bisse_height'),'Figure height (inches)',7,min=4,max=24),
    shiny::downloadButton(ns('bisse_pdf'),'Download graph PDF'),shiny::downloadButton(ns('bisse_png'),'Download graph PNG'),shiny::downloadButton(ns('bisse_script'),'Download graph R code'))),
  shiny::textOutput(ns('bisse_metadata')),shiny::tableOutput(ns('bisse_mapping')),
  shiny::tableOutput(ns('bisse_estimates')),shiny::downloadButton(ns('bisse_csv'),'Download estimates CSV'),
  shiny::p('lambda is speciation, mu is extinction, q01 and q10 are directional transitions. Rates are per branch-length unit.'),
  shiny::tableOutput(ns('bisse_comparison')),shiny::downloadButton(ns('bisse_comparison_csv'),'Download model comparison CSV'),
  shiny::textOutput(ns('bisse_interpretation')),
  shiny::p('AIC weights require compatible, verified, repeatable interior fits. They do not establish causality.'),
  shiny::downloadButton(ns('bisse_rds'),'Download graph settings and result RDS')),
 diagnostics=shiny::tagList(shiny::tableOutput(ns('bisse_profile_interval')),shiny::tableOutput(ns('bisse_profile_curve')),shiny::downloadButton(ns('bisse_profile_csv'),'Download profile CSV'),shiny::downloadButton(ns('bisse_interval_csv'),'Download interval CSV'),shiny::verbatimTextOutput(ns('bisse_warnings')),
  shiny::p('Rates condition on one tree, observed states, sampling fractions and root treatment. Optional profile intervals require verified fits; calibrated likelihood-ratio tests are not provided.'),
  shiny::p('Likelihood slices hold other free rates fixed and respect tied parameters. They are not confidence intervals or nuisance-refitted profiles.'),
  shiny::tableOutput(ns('bisse_diagnostics')),shiny::tableOutput(ns('bisse_attempts')),
  shiny::downloadButton(ns('bisse_attempts_csv'),'Download optimizer diagnostics CSV'),shiny::downloadButton(ns('bisse_slices_csv'),'Download likelihood slices CSV'),
  shiny::h4('Effective parameter constraints'),shiny::tableOutput(ns('bisse_constraints'))),
 mirror=shiny::verbatimTextOutput(ns('bisse_code')))
}
