ui_mod_sse_musse <- function(id) {
 ns<-shiny::NS(id)
 ui_mod_analysis_base(id,'musse','MuSSE',
 controls=shiny::tagList(
  shiny::tags$details(open=TRUE,shiny::tags$summary('Model and data settings'),
   shiny::selectInput(ns('musse_trait'),'Discrete trait',choices=NULL),
   shiny::actionButton(ns('musse_fill_states'),'Fill state table'),
   shiny::textAreaInput(ns('musse_states'),'MuSSE state table (CSV)','',rows=6),
   shiny::p('Columns: State,Sampling,RootWeight. Every observed state must occur once. Row order defines codes 1 to k. Blank uses sorted observed states, complete sampling and equal root weights. RootWeight is used only with ROOT.GIVEN.'),
   shiny::tableOutput(ns('musse_mapping_preview')),
   shiny::p('MuSSE treats each label as one categorical state, not as polymorphism or uncertainty. Two to eight observed states are supported.'),
   shiny::checkboxGroupInput(ns('musse_models'),'Models',choices=guane_musse_models(),selected=c('Equal transitions','Equal diversification and transitions')),
   shiny::p('The default comparison shares one transition rate across states. Full and other constraints remain selectable.'),
   shiny::p('Sampling assumes random inclusion within each state; fractions are treated as known.'),
   shiny::checkboxInput(ns('musse_survival'),'Condition on crown survival and root split',TRUE),
   shiny::selectInput(ns('musse_root'),'Root treatment',c('Observed (ROOT.OBS)'='OBS','Equal (ROOT.FLAT)'='FLAT','Given (ROOT.GIVEN)'='GIVEN')),
   shiny::p('ROOT.OBS uses likelihood-based root weights, not tip frequencies. Root treatment is shared by all candidates.'),
   shiny::p('Equilibrium-root weighting is unavailable in the installed multistate backend.')) ,
  shiny::tags$details(shiny::tags$summary('Advanced fitting controls'),
   shiny::checkboxInput(ns('musse_verify'),'Verify with an independent optimizer',TRUE),
   shiny::actionButton(ns('musse_fill'),'Fill parameter table'),
   shiny::textAreaInput(ns('musse_parameters'),'MuSSE parameter table (CSV)','',rows=9),
   shiny::p('Columns: Parameter,Group,Fixed,Start,Lower,Upper. Use lambda1 through lambdak, mu1 through muk, and qij for directed transitions (source i, destination j). Blank uses tree-scaled defaults. Group and Fixed apply only to Custom; preset models use their own constraints. Shared Group values tie rates; a numeric Fixed value fixes the whole group.'),
   shiny::selectInput(ns('musse_optimizer'),'Optimizer',c('nlminb','L-BFGS-B')),
   shiny::numericInput(ns('musse_starts'),'Optimizer starts',3,min=1,max=8,step=1),
   shiny::numericInput(ns('musse_maxit'),'Maximum iterations',500,min=10,max=5000,step=100),
   shiny::selectInput(ns('musse_backend'),'ODE backend',c('gslode','deSolve'),selected=guane_sse_backend()),
   shiny::numericInput(ns('musse_tol'),'ODE tolerance',1e-8,min=1e-12,max=1e-4),
   shiny::numericInput(ns('musse_eps'),'Integration retry threshold (eps)',0,min=0,max=.001),
   shiny::checkboxInput(ns('musse_slices'),'Save likelihood slices',TRUE)),
  shiny::tags$details(shiny::tags$summary('Profile uncertainty'),
   shiny::p('Choose the model and parameter in Graph controls, then set the profile search bounds.'),
   shiny::numericInput(ns('musse_profile_lower'),'Profile lower search bound',0,min=0),shiny::numericInput(ns('musse_profile_upper'),'Profile upper search bound',1,min=0),
   shiny::numericInput(ns('musse_profile_points'),'Profile grid points',15,min=5,max=101),shiny::numericInput(ns('musse_profile_level'),'Profile confidence level',.95,min=.51,max=.999),
   shiny::actionButton(ns('musse_profile_run'),'Run profile uncertainty')),
  shiny::actionButton(ns('musse_run'),'Run MuSSE'),shiny::textOutput(ns('musse_status')),
  shiny::p('MuSSE support is exploratory: unmodeled rate heterogeneity can mimic trait dependence. Multistate hidden-state null models are not implemented; the hidden-state card supports binary traits only.')),
 results=shiny::tagList(
  shiny::fluidRow(shiny::column(9,shiny::div(class='guane-asr-figure',shiny::plotOutput(ns('musse_plot'),height='auto'))),
   shiny::column(3,shiny::h4('Graph controls'),
    shiny::selectInput(ns('musse_graph'),'Graph',c('Rate estimates'='rates','Observed tip states'='tree','Transition rates'='transitions','Model comparison'='comparison','Optimizer starts'='starts','Independent optimizer verification'='verification','Likelihood slice'='slice','Profile likelihood'='profile')),
    shiny::selectInput(ns('musse_plot_model'),'Model',choices='Equal transitions'),
    shiny::selectInput(ns('musse_plot_parameter'),'Parameter',choices=NULL),
    shiny::selectInput(ns('musse_palette'),'Palette',c('Guane','Legacy','Grayscale')),
    shiny::checkboxInput(ns('musse_labels'),'Show tip labels',TRUE),
    shiny::numericInput(ns('musse_font'),'Label size',.7,min=.2,max=2,step=.1),
    shiny::numericInput(ns('musse_width'),'Figure width (inches)',10,min=5,max=24),
    shiny::numericInput(ns('musse_height'),'Figure height (inches)',7,min=4,max=24),
    shiny::downloadButton(ns('musse_pdf'),'Download graph PDF'),shiny::downloadButton(ns('musse_png'),'Download graph PNG'),shiny::downloadButton(ns('musse_script'),'Download graph R code'))),
  shiny::textOutput(ns('musse_metadata')),shiny::tableOutput(ns('musse_mapping')),
  shiny::tableOutput(ns('musse_estimates')),shiny::downloadButton(ns('musse_csv'),'Download estimates CSV'),
  shiny::p('lambdai is speciation, mui is extinction, and qij is the transition from state i to j. Rates are per branch-length unit.'),
  shiny::tableOutput(ns('musse_comparison')),shiny::downloadButton(ns('musse_comparison_csv'),'Download model comparison CSV'),
  shiny::textOutput(ns('musse_interpretation')),
  shiny::p('AIC weights require compatible, verified, repeatable interior fits. They do not establish causality.'),
  shiny::downloadButton(ns('musse_rds'),'Download graph settings and result RDS')),
 diagnostics=shiny::tagList(shiny::tableOutput(ns('musse_profile_interval')),shiny::tableOutput(ns('musse_profile_curve')),shiny::downloadButton(ns('musse_profile_csv'),'Download profile CSV'),shiny::downloadButton(ns('musse_interval_csv'),'Download interval CSV'),shiny::verbatimTextOutput(ns('musse_warnings')),
  shiny::p('Rates condition on one tree, observed states, sampling fractions and root treatment. Optional profile intervals require verified fits; calibrated likelihood-ratio tests are not provided.'),
  shiny::p('Likelihood slices hold other free rates fixed and respect tied parameters. They are not confidence intervals or nuisance-refitted profiles.'),
  shiny::tableOutput(ns('musse_diagnostics')),shiny::tableOutput(ns('musse_attempts')),
  shiny::downloadButton(ns('musse_attempts_csv'),'Download optimizer diagnostics CSV'),shiny::downloadButton(ns('musse_slices_csv'),'Download likelihood slices CSV'),
  shiny::h4('Effective parameter constraints'),shiny::tableOutput(ns('musse_constraints'))),
 mirror=shiny::verbatimTextOutput(ns('musse_code')))
}
