ui_mod_div_clades <- function(id) {
 ns<-shiny::NS(id)
 ui_mod_analysis_base(id,'clades','Clade-specific models',
 controls=shiny::tagList(
shiny::tags$details(open=TRUE,shiny::tags$summary('Model and data settings'),
  shiny::p('Select non-overlapping internal nodes. Each crown must contain at least four sampled tips. All descendants are retained; ancestral stems are excluded.'),
  shiny::selectizeInput(ns('clade_nodes'),'Crown nodes',choices=NULL,multiple=TRUE),
  shiny::actionButton(ns('clade_preview_run'),'Preview selected clades'),
  shiny::textAreaInput(ns('clade_sampling'),'Clade sampling fractions (CSV)',value='',rows=4),
  shiny::actionButton(ns('clade_fill'),'Fill sampling table'),
  shiny::p('Columns: Node,Sampling. Blank means complete sampling (1) for each selected clade. Enter the probability of random extant-taxon inclusion within each clade.'),
  shiny::checkboxGroupInput(ns('clade_models'),'Models',c('Yule (mu = 0)'='Yule','Birth-death'='BD'),selected=c('Yule','BD')),
  shiny::checkboxInput(ns('clade_survival'),'Condition on crown survival and root split',TRUE)),
shiny::tags$details(shiny::tags$summary('Advanced fitting controls'),
  shiny::selectInput(ns('clade_optimizer'),'Optimizer',c('nlminb','L-BFGS-B')),
  shiny::numericInput(ns('clade_maxit'),'Maximum iterations',2000,min=10,max=20000,step=100),
  shiny::textInput(ns('clade_upper'),'Rate upper bound (blank = 100 / crown age)',''),
  shiny::textInput(ns('clade_start_lambda'),'Initial lambda (blank = derived)',''),
  shiny::textInput(ns('clade_start_mu'),'Initial mu (blank = lambda / 2)',''),
  shiny::p('Several deterministic starts are tried. Extinction may exceed speciation; no positive net-diversification constraint is imposed.'),
  shiny::checkboxInput(ns('clade_intervals'),'Calculate approximate curvature intervals',TRUE),
  shiny::checkboxInput(ns('clade_slices'),'Save likelihood slices',TRUE),
  shiny::p('Clade fits use Models, conditioning, optimizer, bounds, starts and interval/slice controls above. Blank bounds and starts are derived separately for each crown. The whole-tree sampling fraction is not used.')),
shiny::tags$details(shiny::tags$summary('Uncertainty and diagnostics'),
  shiny::checkboxInput(ns('clade_profiles'),'Calculate clade profiles',TRUE),
  shiny::numericInput(ns('clade_level'),'Clade profile reference level',.95,min=.8,max=.99,step=.01),
  shiny::numericInput(ns('clade_points'),'Clade profile grid points',31,min=21,max=201,step=10)),
  shiny::actionButton(ns('clade_run'),'Run clade models'),shiny::textOutput(ns('clade_status'))),
 results=shiny::tagList(shiny::fluidRow(
  shiny::column(9,shiny::div(class='guane-asr-figure',shiny::plotOutput(ns('clade_plot'),height='auto'))),
  shiny::column(3,shiny::h4('Graph controls'),
shiny::selectInput(ns('clade_graph'),'Graph',c('Selected crown clades'='clade_tree','Clade-specific rate estimates'='clade_rates','Within-clade model comparison'='clade_comparison','Clade profile likelihood'='clade_profile','Clade likelihood slice'='clade_slice')),
   shiny::selectInput(ns('clade_plot_model'),'Model',c('Yule','BD')),
   shiny::selectInput(ns('clade_parameter'),'Parameter',c('lambda','mu','net')),
   shiny::selectInput(ns('clade_palette'),'Palette',c('Guane','Legacy','Grayscale')),
   shiny::selectInput(ns('clade_plot_node'),'Saved clade for diagnostics',choices=NULL),
   shiny::checkboxInput(ns('clade_labels'),'Show clade tip labels',TRUE),
   shiny::checkboxInput(ns('clade_node_labels'),'Show eligible node numbers',TRUE),
   shiny::numericInput(ns('clade_cex'),'Clade label size',.7,min=.2,max=2,step=.1),
   shiny::downloadButton(ns('clade_pdf'),'Download graph PDF'),shiny::downloadButton(ns('clade_png'),'Download graph PNG'),shiny::downloadButton(ns('clade_script'),'Download graph R code'))),
  shiny::h4('Clade-specific results'),shiny::textOutput(ns('clade_interpretation')),
  shiny::p('These are separate crown-clade fits, not a joint rate-shift test. DeltaAIC and weights compare models within each clade only. Do not rank likelihoods or AIC across different clades. Selecting clades after inspecting rates introduces selection bias.'),
  shiny::tableOutput(ns('clade_summary')),shiny::tableOutput(ns('clade_estimates')),shiny::tableOutput(ns('clade_comparison')),
  shiny::downloadButton(ns('clade_estimates_csv'),'Download clade estimates CSV'),
  shiny::downloadButton(ns('clade_comparison_csv'),'Download within-clade comparison CSV'),
  shiny::downloadButton(ns('clade_members_csv'),'Download clade membership CSV'),
  shiny::downloadButton(ns('clade_manifest_csv'),'Download clade settings CSV'),
  shiny::downloadButton(ns('clade_trees'),'Download selected crown trees'),
shiny::downloadButton(ns('clade_rds'),'Download graph settings and result RDS')),
 diagnostics=shiny::tagList(
  shiny::h4('Clade diagnostics'),shiny::tableOutput(ns('clade_audit')),
  shiny::p('Small clades often provide weak information about extinction. Inspect boundaries, optimizer starts and profile search limits. Intervals condition on the chosen clades, topology, branch lengths and sampling fractions.'),
  shiny::tableOutput(ns('clade_profile_table')),shiny::tableOutput(ns('clade_attempts')),
  shiny::downloadButton(ns('clade_audit_csv'),'Download clade audit CSV'),
  shiny::downloadButton(ns('clade_attempts_csv'),'Download clade optimizer CSV'),
  shiny::downloadButton(ns('clade_profiles_csv'),'Download clade profiles CSV'),
  shiny::downloadButton(ns('clade_profile_curves_csv'),'Download clade profile curves CSV'),
  shiny::downloadButton(ns('clade_slices_csv'),'Download clade slices CSV')),
 mirror=shiny::verbatimTextOutput(ns('clade_code')))
}
