ui_mod_div_time <- function(id) {
 ns<-shiny::NS(id)
 ui_mod_analysis_base(id,'time','Time-varying models',
 controls=shiny::tagList(
shiny::tags$details(open=TRUE,shiny::tags$summary('Model and data settings'),
  shiny::p('Uses the tree from Data; a trait table is not required.'),
  shiny::checkboxGroupInput(ns('time_models'),'Time-comparison candidates',c('Yule','BD','ExpYule','ExpBD'),selected=c('Yule','BD','ExpYule','ExpBD')),
  shiny::p('ExpYule: exponential speciation, zero extinction. ExpBD: exponential speciation, constant extinction. lambda(t) = lambda0 * exp(-beta * t), with t measured backward from the present. Positive beta means increasing speciation toward the present.'),
  shiny::numericInput(ns('time_sampling'),'Random extant sampling fraction',1,min=.000001,max=1,step=.01),
  shiny::checkboxInput(ns('time_survival'),'Condition on crown survival and root split',TRUE),
  shiny::p('Sampling assumes independent random inclusion of extant species. Nonrandom or diversified sampling is not modeled.')),
shiny::tags$details(shiny::tags$summary('Advanced fitting controls'),
  shiny::selectInput(ns('time_optimizer'),'Optimizer',c('nlminb','L-BFGS-B')),
  shiny::numericInput(ns('time_maxit'),'Maximum iterations',2000,min=10,max=20000,step=100),
  shiny::textInput(ns('time_upper'),'Rate upper bound (blank = 100 / crown age)',''),
  shiny::textInput(ns('time_start_lambda'),'Initial lambda (blank = derived)',''),
  shiny::textInput(ns('time_start_mu'),'Initial mu (blank = lambda / 2)',''),
  shiny::p('Several deterministic starts are tried. Extinction may exceed speciation; no positive net-diversification constraint is imposed.'),
  shiny::numericInput(ns('time_beta'),'Initial beta (per branch-length unit)',0),
  shiny::numericInput(ns('time_bound'),'Absolute bound on beta times crown age',3,min=.01,max=10,step=.5),
  shiny::numericInput(ns('time_tol'),'ODE tolerance',1e-8,min=1e-10,max=1e-5),
  shiny::selectInput(ns('time_backend'),'ODE solver',c('gslode','deSolve')),
  shiny::p('Uses the sampling, conditioning, optimizer and rate starts above. The rate upper bound limits present-day speciation and constant extinction; ancestral speciation can exceed it. All comparison candidates use the same ODE likelihood.')),
  shiny::actionButton(ns('time_run'),'Run time-varying comparison'),
shiny::textOutput(ns('time_status')),
shiny::tags$details(shiny::tags$summary('Uncertainty and diagnostics'),
  shiny::selectInput(ns('time_unc_model'),'Time model to diagnose',c('ExpYule','ExpBD','Yule','BD')),
  shiny::checkboxInput(ns('time_profiles'),'Time-model profiles',TRUE),
  shiny::numericInput(ns('time_level'),'Profile reference level',.95,min=.8,max=.99,step=.01),
  shiny::numericInput(ns('time_points'),'Time profile grid points',31,min=21,max=101,step=10),
  shiny::checkboxInput(ns('time_bootstrap'),'Conditional parametric bootstrap',TRUE),
  shiny::numericInput(ns('time_nsim'),'Bootstrap replicates',50,min=20,max=500,step=10),
  shiny::numericInput(ns('time_seed'),'Simulation seed',999,min=0,max=2147483647),
  shiny::checkboxInput(ns('time_robustness'),'Check starts, bounds and tolerance',TRUE),
  shiny::numericInput(ns('time_factor'),'Robustness bound multiplier',2,min=1.1,max=4,step=.5),
  shiny::actionButton(ns('time_unc_run'),'Run time-model uncertainty'))),
 results=shiny::tagList(shiny::fluidRow(
  shiny::column(9,shiny::div(class='guane-asr-figure',shiny::plotOutput(ns('time_plot'),height='auto'))),
  shiny::column(3,shiny::h4('Graph controls'),
shiny::selectInput(ns('time_graph'),'Graph',c('Rates through time'='time_rates','Time-model comparison'='time_comparison','Time-model profile likelihood'='time_profile','Conditional bootstrap refits'='time_bootstrap','Time-model robustness'='time_robustness')),
   shiny::selectInput(ns('time_plot_model'),'Model',c('Yule','BD','ExpYule','ExpBD')),
   shiny::selectInput(ns('time_parameter'),'Parameter',c('lambda','mu','net','beta')),
   shiny::selectInput(ns('time_palette'),'Palette',c('Guane','Legacy','Grayscale')),
   shiny::downloadButton(ns('time_pdf'),'Download graph PDF'),shiny::downloadButton(ns('time_png'),'Download graph PNG'),shiny::downloadButton(ns('time_script'),'Download graph R code'))),
  shiny::h4('Time-model results'),shiny::textOutput(ns('time_interpretation')),shiny::tableOutput(ns('time_comparison')),
  shiny::p('Rates through time shows fitted trajectories. Conditional bootstrap bands are available after Run time-model uncertainty. AIC weights describe the selected candidate set, not model adequacy.'),
  shiny::downloadButton(ns('time_csv'),'Download time comparison CSV'),shiny::downloadButton(ns('time_curves_csv'),'Download rate trajectories CSV'),
  shiny::p('lambda is speciation, mu is extinction, and net is lambda minus mu. Rates are per branch-length unit, not automatically per million years.'),
shiny::downloadButton(ns('time_rds'),'Download graph settings and result RDS')),
 diagnostics=shiny::tagList(
  shiny::h4('Time-model uncertainty and robustness'),
  shiny::verbatimTextOutput(ns('time_unc_warnings')),shiny::p('Time profiles reoptimize nuisance parameters within saved bounds. Search limits and nuisance-bound flags are not infinite intervals. Reference coverage is approximate, especially at boundaries.'),
  shiny::tableOutput(ns('time_profile_table')),shiny::downloadButton(ns('time_unc_csv'),'Download time profile intervals CSV'),
  shiny::downloadButton(ns('time_profile_curves_csv'),'Download time profile curves CSV'),
  shiny::p('Bootstrap refits fix crown age, sampled tip count and sampling fraction. The pointwise 95% envelope summarizes successful conditional refits, not calibrated confidence coverage or model-selection uncertainty. Bands require at least 20 successful refits and 90% success. Inspect failures and boundary frequency.'),
  shiny::textOutput(ns('time_boot_summary')),shiny::tableOutput(ns('time_boot_table')),
  shiny::downloadButton(ns('time_boot_csv'),'Download bootstrap refits CSV'),shiny::downloadButton(ns('time_bands_csv'),'Download bootstrap bands CSV'),
  shiny::p('Robustness refits change starts, expand bounds and tighten ODE tolerance separately. A better likelihood means the original fit needs review. These scenarios do not prove a global optimum.'),
  shiny::tableOutput(ns('time_robust_table')),shiny::downloadButton(ns('time_robust_csv'),'Download robustness CSV'),
  shiny::h4('Time-model diagnostics'),shiny::verbatimTextOutput(ns('time_warnings')),
  shiny::p('Tolerance_delta compares the saved likelihood with a tenfold tighter ODE tolerance. Weights are withheld above 0.0001 or on failure. Inspect all starts and boundary flags.'),
  shiny::tableOutput(ns('time_attempts')),shiny::downloadButton(ns('time_attempts_csv'),'Download time optimizer CSV')),
 mirror=shiny::verbatimTextOutput(ns('time_code')))
}
