ui_mod_div_joint <- function(id) {
 ns<-shiny::NS(id)
 ui_mod_analysis_base(id,'joint','Joint clade-dependent models',
 controls=shiny::tagList(
shiny::tags$details(open=TRUE,shiny::tags$summary('Model and data settings'),
  shiny::selectizeInput(ns('joint_nodes'),'Joint shift nodes',choices=NULL,multiple=TRUE),
  shiny::p('Shift placement: branch base (split.t = Inf). Other timings are unsupported by the installed backend. Nested regions are allowed; each region must retain at least two sampled tips.'),
  shiny::textAreaInput(ns('joint_sampling'),'Joint region sampling (CSV)','',rows=4),
  shiny::actionButton(ns('joint_fill'),'Fill joint region tables'),
  shiny::p('Use Region,Sampling: background is 0; other region identifiers are shift nodes. Blank means sampling 1 everywhere. Whole-tree and separate-clade sampling controls do not apply.'),
  shiny::checkboxGroupInput(ns('joint_models'),'Joint candidates',c('SharedYule','SharedBD','ShiftLambda','ShiftMu','ShiftBoth','Custom'),selected=c('SharedYule','SharedBD','ShiftLambda','ShiftMu','ShiftBoth')),
  shiny::p('SharedYule fixes extinction to zero. SharedBD shares both rates. ShiftLambda, ShiftMu and ShiftBoth vary the named rates across regions.'),
  shiny::checkboxInput(ns('joint_survival'),'Condition on crown survival and root split',TRUE)),
shiny::tags$details(shiny::tags$summary('Advanced fitting controls'),
  shiny::selectInput(ns('joint_optimizer'),'Optimizer',c('nlminb','L-BFGS-B')),
  shiny::numericInput(ns('joint_maxit'),'Maximum iterations',2000,min=10,max=20000,step=100),
  shiny::textInput(ns('joint_upper'),'Rate upper bound (blank = 100 / crown age)',''),
  shiny::textAreaInput(ns('joint_custom'),'Custom joint constraints (CSV)','',rows=4),
  shiny::p('Columns: Region,Lambda,Mu. Equal parameter names share a rate; numbers fix rates. Fixed speciation must be positive. Do not reuse a name across speciation and extinction. Used only for Custom.'),
  shiny::textAreaInput(ns('joint_controls'),'Joint parameter controls (CSV)','',rows=4),
  shiny::p('Optional columns: Parameter,Start,Lower,Upper. Names appear in the constraints table. Unlisted parameters use derived starts and the upper bound above. Free speciation lower bounds must be positive; starts must lie strictly inside bounds.'),
  shiny::p('Joint models use conditioning, optimizer, maximum iterations, upper bound and curvature interval controls above. All candidates share one partitioned whole-tree likelihood. Shift positions and sampling are fixed, not estimated.')),
shiny::tags$details(shiny::tags$summary('Uncertainty and diagnostics'),
  shiny::checkboxInput(ns('joint_intervals'),'Calculate approximate curvature intervals',TRUE)),
  shiny::actionButton(ns('joint_preview'),'Preview joint regions'),shiny::actionButton(ns('joint_run'),'Run joint models'),shiny::textOutput(ns('joint_status'))),
 results=shiny::tagList(shiny::fluidRow(
  shiny::column(9,shiny::div(class='guane-asr-figure',shiny::plotOutput(ns('joint_plot'),height='auto'))),
  shiny::column(3,shiny::h4('Graph controls'),
shiny::selectInput(ns('joint_graph'),'Graph',c('Joint diversification regions'='joint_tree','Joint regional rates'='joint_rates','Joint whole-tree model comparison'='joint_comparison','Joint optimizer agreement'='joint_attempts')),
   shiny::selectInput(ns('joint_plot_model'),'Joint model to display',c('SharedYule','SharedBD','ShiftLambda','ShiftMu','ShiftBoth','Custom'),selected='SharedBD'),
   shiny::selectInput(ns('joint_parameter'),'Parameter',c('lambda','mu','net')),
   shiny::selectInput(ns('joint_palette'),'Palette',c('Guane','Legacy','Grayscale')),
   shiny::checkboxInput(ns('joint_labels'),'Show clade tip labels',TRUE),
   shiny::checkboxInput(ns('joint_node_labels'),'Show eligible node numbers',TRUE),
   shiny::numericInput(ns('joint_cex'),'Clade label size',.7,min=.2,max=2,step=.1),
   shiny::downloadButton(ns('joint_pdf'),'Download graph PDF'),shiny::downloadButton(ns('joint_png'),'Download graph PNG'),shiny::downloadButton(ns('joint_script'),'Download graph R code'))),
  shiny::h4('Joint model results'),shiny::textOutput(ns('joint_interpretation')),
  shiny::p('Joint AIC compares these candidates on the same whole-tree likelihood only. It does not include uncertainty in shift selection, sampling or the tree. No calibrated likelihood-ratio p-value is reported.'),
  shiny::tableOutput(ns('joint_regions')),shiny::tableOutput(ns('joint_comparison')),shiny::tableOutput(ns('joint_estimates')),
  shiny::downloadButton(ns('joint_comparison_csv'),'Download joint comparison CSV'),shiny::downloadButton(ns('joint_estimates_csv'),'Download joint estimates CSV'),shiny::downloadButton(ns('joint_membership_csv'),'Download joint membership CSV'),shiny::downloadButton(ns('joint_edges_csv'),'Download joint branch regions CSV'),
shiny::downloadButton(ns('joint_rds'),'Download graph settings and result RDS')),
 diagnostics=shiny::tagList(
  shiny::h4('Joint model diagnostics'),shiny::verbatimTextOutput(ns('joint_warnings')),
  shiny::p('Intervals are approximate curvature intervals, withheld at bounds or unstable curvature. Joint regions with little information can have weakly identified rates. Inspect all optimizer starts.'),
  shiny::tableOutput(ns('joint_constraints')),shiny::tableOutput(ns('joint_controls_table')),shiny::tableOutput(ns('joint_attempts')),
  shiny::downloadButton(ns('joint_constraints_csv'),'Download joint constraints CSV'),shiny::downloadButton(ns('joint_controls_csv'),'Download joint controls CSV'),shiny::downloadButton(ns('joint_attempts_csv'),'Download joint optimizer CSV'),shiny::downloadButton(ns('joint_regions_csv'),'Download joint sampling CSV')),
 mirror=shiny::verbatimTextOutput(ns('joint_code')))
}
