ui_mod_asr_discrete <- function(id) {
 ns<-shiny::NS(id)
 ui_mod_analysis_base(id,'discrete','Discrete traits',
 controls=shiny::tagList(
  shiny::selectInput(ns('mk_trait'),'Trait for reconstruction',NULL),
  shiny::selectInput(ns('mk_framework'),'Framework',c('Maximum likelihood'='ML','Stochastic mapping (fixed fitted rates)'='simmap','Bayesian Mk (sample rates)'='Bayes','Parsimony — planned'='parsimony')),
  shiny::selectInput(ns('mk_model'),'Model',c('ER','SYM','ARD','Custom')),
  shiny::p('ER shares all rates; SYM shares reverse rates; ARD estimates each directed rate.'),
  shiny::p('Use 2 to 10 observed states. Numeric states must be integers. Polymorphic characters belong in their own card.'),
  
  shiny::textOutput(ns('mk_states')),
  shiny::conditionalPanel(sprintf("input['%s'] == 'Custom'",ns('mk_model')),
   shiny::selectInput(ns('mk_template'),'Start custom matrix from',c('ER','SYM','ARD')),
   shiny::actionButton(ns('mk_fill'),'Fill custom matrix'),
   shiny::textAreaInput(ns('mk_custom'),'Custom rate constraints',value='',rows=7,width='100%'),
   shiny::p('Rows are source states; columns are destination states, in the displayed order. Use 0 for forbidden transitions and the diagonal. Equal positive integers share a rate; use consecutive indices starting at 1. Enter comma-separated rows without headers.'),
   shiny::div(style='overflow-x:auto',shiny::tableOutput(ns('mk_matrix'))),shiny::textOutput(ns('mk_matrix_status'))),
  shiny::conditionalPanel(sprintf("input['%s'] != 'Bayes'",ns('mk_framework')),
   ui_asr_reconstruction(ns,'mk'),ui_asr_mk_advanced(ns,'mk'),
   shiny::checkboxInput(ns('mk_compare'),'Compare with ER, SYM and ARD',TRUE)),
  ui_asr_bayes_controls(ns,'mk'),
  shiny::conditionalPanel(sprintf("input['%s'] == 'simmap'",ns('mk_framework')),
   shiny::numericInput(ns('mk_nsim'),'Number of histories',100,min=2,max=500,step=1),
   shiny::numericInput(ns('mk_seed'),'Mapping seed',999,min=0,max=2147483646,step=1),
   shiny::p('Histories are conditional on the fitted Q matrix, observed tips, tree and the selected root probabilities. Rates and trees are not sampled. There is no MCMC burn-in.')),
  shiny::actionButton(ns('mk_run'),'Run Mk reconstruction'),shiny::textOutput(ns('mk_status'))),
 results=shiny::tagList(shiny::fluidRow(
  shiny::column(9,shiny::div(class='guane-asr-figure',shiny::plotOutput(ns('mk_plot'),height='auto'))),
  shiny::column(3,shiny::h4('Graph controls'),
   shiny::selectInput(ns('mk_graph'),'Graph',c('Node probability tree'='tree','Transition-rate diagram'='rates','Marginal state probabilities'='probabilities','Model comparison'='comparison','Optimizer starts'='starts')),
   shiny::conditionalPanel(sprintf("input['%s'] == 'simmap' || input['%s'] == 'Bayes'",ns('mk_framework'),ns('mk_framework')),shiny::numericInput(ns('mk_history'),'History to display',1,min=1,step=1)),
   shiny::conditionalPanel(sprintf("input['%s'] == 'Bayes'",ns('mk_framework')),shiny::selectInput(ns('mk_bayes_parameter'),'Posterior parameter',c('q1','logLik'))),
   shiny::selectInput(ns('mk_palette'),'Palette',c('Guane','Legacy','Grayscale')),
   shiny::checkboxInput(ns('mk_labels'),'Show tip labels',TRUE),shiny::checkboxInput(ns('mk_nodes'),'Show node numbers',FALSE),
   shiny::sliderInput(ns('mk_label_size'),'Label size',min=.3,max=1.2,value=.7,step=.1),
   shiny::sliderInput(ns('mk_pie_size'),'Node pie size',min=.2,max=1.5,value=.6,step=.1),
   ui_asr_graphics(ns,'mk',continuous=FALSE),
   shiny::downloadButton(ns('mk_pdf'),'Download graph PDF'),shiny::downloadButton(ns('mk_script'),'Download graph R code'))),
  shiny::h4('Selected node'),shiny::tableOutput(ns('mk_node_detail')),shiny::downloadButton(ns('mk_node_csv'),'Download selected node CSV'),
  shiny::textOutput(ns('mk_metadata')),
  shiny::conditionalPanel(sprintf("input['%s'] == 'density'",ns('mk_graph')),shiny::downloadButton(ns('mk_density_csv'),'Download density segments CSV')),

  shiny::conditionalPanel(sprintf("input['%s'] == 'simmap' || input['%s'] == 'Bayes'",ns('mk_framework'),ns('mk_framework')),
   shiny::textOutput(ns('mk_mapping_info')),
   shiny::conditionalPanel(sprintf("input['%s'] != 'Bayes'",ns('mk_framework')),shiny::p('Simulation ranges describe the central 95% of sampled histories, not confidence intervals for the mean or uncertainty in fitted rates. MCSE measures Monte Carlo precision; small samples and zero sampled events can be misleading.')),
   shiny::h4('Transition counts'),shiny::div(style='overflow-x:auto',shiny::tableOutput(ns('mk_transitions'))),
   shiny::downloadButton(ns('mk_transitions_csv'),'Download transition summary CSV'),
   shiny::h4('State occupancy'),shiny::div(style='overflow-x:auto',shiny::tableOutput(ns('mk_occupancy'))),
   shiny::downloadButton(ns('mk_occupancy_csv'),'Download state occupancy CSV'),
   shiny::downloadButton(ns('mk_frequency_csv'),'Download sampled node frequencies CSV'),
   shiny::downloadButton(ns('mk_maps_rds'),'Download histories and summaries RDS')), shiny::textOutput(ns('mk_interpretation')),
  shiny::conditionalPanel(sprintf("input['%s'] != 'Bayes'",ns('mk_framework')),shiny::p('Node pies show marginal state probabilities conditional on the fitted rates, tree and the selected root probabilities. They do not integrate parameter or tree uncertainty and are not sampled evolutionary histories.')),
  shiny::conditionalPanel(sprintf("input['%s'] == 'joint' && input['%s'] != 'Bayes'",ns('mk_reconstruction'),ns('mk_framework')),shiny::h4('Joint ancestral assignments'),shiny::tableOutput(ns('mk_joint')),shiny::textOutput(ns('mk_joint_info')),shiny::downloadButton(ns('mk_joint_csv'),'Download joint assignments CSV'),
  shiny::p('Joint assignments maximize the simultaneous ancestral configuration. Ties may occur; assignments are not probabilities.')),
  ui_asr_bayes_results(ns,'mk'),
  shiny::downloadButton(ns('mk_results_rds'),'Download analysis RDS'),
  shiny::h4('Marginal state probabilities'),shiny::div(style='overflow-x:auto',shiny::tableOutput(ns('mk_probabilities'))),
  shiny::downloadButton(ns('mk_csv'),'Download node probabilities CSV'),
  shiny::h4('Selected Q matrix'),shiny::p('Rows are source states; columns are destination states. Off-diagonal rates are per branch-length unit; diagonal entries are negative row sums.'),shiny::div(style='overflow-x:auto',shiny::tableOutput(ns('mk_q'))),shiny::downloadButton(ns('mk_q_csv'),'Download rate matrix CSV')),
 diagnostics=shiny::tagList(
  shiny::conditionalPanel(sprintf("input['%s'] == 'simmap'",ns('mk_framework')),
   shiny::h4('Monte Carlo agreement'),shiny::div(class='guane-asr-figure',shiny::plotOutput(ns('mk_mc_plot'),height='auto')),
   shiny::downloadButton(ns('mk_mc_pdf'),'Download graph PDF'),shiny::downloadButton(ns('mk_mc_script'),'Download graph R code'),
   shiny::p('Compare sampled node frequencies with analytic marginal probabilities. Differences should decrease with more independent histories; this plot is not an MCMC convergence or model-adequacy test.'),
   shiny::div(style='overflow-x:auto',shiny::tableOutput(ns('mk_mc_table')))),
  shiny::conditionalPanel(sprintf("input['%s'] != 'Bayes'",ns('mk_framework')),shiny::p('Starting values and effective calls are recorded per model. Convergence does not establish identifiability or model adequacy. Near-boundary rates and different optima require caution.')),
  shiny::verbatimTextOutput(ns('mk_warnings')),
  shiny::conditionalPanel(sprintf("input['%s'] != 'Bayes'",ns('mk_framework')),shiny::h4('Model comparison'),shiny::div(class='guane-asr-figure',shiny::plotOutput(ns('mk_diagnostics'),height='auto')),
  shiny::downloadButton(ns('mk_diagnostic_pdf'),'Download graph PDF'),shiny::downloadButton(ns('mk_diagnostic_script'),'Download graph R code'),shiny::div(style='overflow-x:auto',shiny::tableOutput(ns('mk_comparison'))),
  shiny::p('AIC comparisons use the same taxa, trait, tree and the selected root probabilities. Weights describe only distinct converged candidates; equivalent constraints are omitted. Failed candidates remain visible. No model averaging is performed.'),
  shiny::downloadButton(ns('mk_comparison_csv'),'Download model comparison CSV'),
  shiny::h4('Optimizer starts'),shiny::div(style='overflow-x:auto',shiny::tableOutput(ns('mk_attempts'))),
  shiny::downloadButton(ns('mk_attempts_csv'),'Download optimizer diagnostics CSV'),
  shiny::p('Select Model comparison or Optimizer starts in Graph controls to view and export diagnostic plots.')), 
  ui_asr_bayes_diagnostics(ns,'mk')),

 mirror=shiny::verbatimTextOutput(ns('mk_code')))
}
