ui_mod_asr_continuous <- function(id) {
 ns<-shiny::NS(id)
 ui_mod_analysis_base(id,'continuous','Continuous traits',
 controls=shiny::tagList(
  shiny::selectInput(ns('bm_trait'),'Trait for reconstruction',NULL),
  shiny::selectInput(ns('bm_framework'),'Framework',c('Maximum likelihood'='ML','Bayesian BM'='Bayes','Parsimony — planned'='parsimony')),
  shiny::conditionalPanel("input.bm_framework == 'Bayes'",ns=ns,
   shiny::p('Bayesian BM samples diffusion and ancestral states on a fixed tree. Tip observations are treated as exact; measurement-error settings from ML do not apply.'),
   shiny::numericInput(ns('bm_ngen'),'MCMC generations per chain',50000,min=100,max=2000000,step=1000),
   shiny::numericInput(ns('bm_sample'),'Save every N generations',100,min=1,step=1),
   shiny::numericInput(ns('bm_burnin'),'Burn-in generations',10000,min=0,step=1000),
   shiny::numericInput(ns('bm_chains'),'Chains',2,min=1,max=4,step=1),
   shiny::numericInput(ns('bm_seed'),'MCMC seed',999,min=0,max=2147483642,step=1),
   shiny::numericInput(ns('bm_spread'),'Chain starting spread',2,min=0,max=10,step=.25),
   shiny::p('Only saved draws with generation greater than burn-in are retained. Short runs are exploratory; defaults do not guarantee convergence.'),
   shiny::actionButton(ns('bm_fill_parameters'),'Fill Bayesian parameter table'),
   shiny::textAreaInput(ns('bm_parameters'),'Priors, starts and proposals (CSV)',rows=8),
   shiny::p('Rows: sig2, then root and internal node numbers. Columns: Parameter, Start, PriorMean, PriorVariance, ProposalVariance. The sig2 prior is exponential: its variance entry must be NA. Node priors are independent normal distributions. Proposal entries are variances, not standard deviations. Blank uses the displayed backend defaults.'),
   shiny::tags$details(shiny::tags$summary('Effective Bayesian controls'),shiny::verbatimTextOutput(ns('bm_bayes_preview')))),
  shiny::conditionalPanel("input.bm_framework != 'Bayes'",ns=ns,
  shiny::selectInput(ns('bm_model'),'Model',c('Brownian motion (BM)'='BM','Ornstein–Uhlenbeck (OU)'='OU','Early burst (EB)'='EB')),
  shiny::checkboxInput(ns('bm_marginal'),'Use comparable marginal ML',TRUE),
  shiny::conditionalPanel("input.bm_marginal",ns=ns,
   shiny::selectInput(ns('bm_se'),'Known standard-error column',c('None (zero error)'='')),
   shiny::p('Supply standard errors, not variances, on the selected trait scale. Errors are squared once and added only to observed-tip variances; they are not automatically transformed.'),
   shiny::checkboxInput(ns('bm_compare'),'Compare BM, OU and EB using marginal ML',FALSE),
   shiny::conditionalPanel("input.bm_model != 'BM'",ns=ns,
    shiny::textInput(ns('bm_shape_lower'),'Shape lower bound (blank = default)',''),
    shiny::textInput(ns('bm_shape_upper'),'Shape upper bound (blank = default)',''),shiny::p('Set both bounds, or leave both blank for defaults. Shape means alpha for OU and r for EB, in inverse branch-length units.')),
   shiny::p('OU uses one optimum equal to the root mean. Prediction intervals condition on fitted covariance parameters. Comparison uses the same taxa, trait scale and known errors; other models use their default bounds.')),
  shiny::conditionalPanel("!input.bm_marginal && input.bm_model == 'BM'",ns=ns,
   shiny::selectInput(ns('bm_engine'),'BM engine',c('BM analytic ML (fastAnc)'='fastAnc','Joint ML (anc.ML)'='anc.ML'))),
  shiny::conditionalPanel("input.bm_marginal || input.bm_model != 'BM' || input.bm_engine == 'anc.ML'",ns=ns,
   shiny::numericInput(ns('bm_maxit'),'Maximum iterations (maxit)',2000,min=1,max=100000,step=100),
   shiny::conditionalPanel("!input.bm_marginal",ns=ns,shiny::textInput(ns('bm_tol'),'Positive parameter lower bound (tol; blank = backend default)','')),
   shiny::checkboxInput(ns('bm_trace'),'Print optimizer trace',FALSE),
   shiny::conditionalPanel("input.bm_marginal || input.bm_model != 'OU'",ns=ns,shiny::checkboxInput(ns('bm_intervals'),'Calculate approximate 95% node intervals',TRUE)),
   shiny::conditionalPanel("input.bm_model != 'BM'",ns=ns,shiny::textInput(ns('bm_start'),'Initial alpha (OU) or r (EB); blank = backend default','')),
   shiny::conditionalPanel("!input.bm_marginal",ns=ns,shiny::p('Legacy anc.ML has no OU intervals or enabled measurement error. Use marginal ML for these features.')))),
  shiny::p('Choose an original or transformed numeric trait. Reconstruction stays on that scale; no automatic back-transformation is applied.'),
  shiny::actionButton(ns('bm_run'),'Run continuous reconstruction'),shiny::textOutput(ns('bm_status'))),
 results=shiny::tagList(shiny::fluidRow(
  shiny::column(9,shiny::div(class='guane-asr-figure',shiny::plotOutput(ns('bm_plot'),height='auto'))),
  shiny::column(3,shiny::h4('Graph controls'),
   shiny::selectInput(ns('bm_graph'),'Graph',c('Trait map'='map','Phenogram'='phenogram','Node intervals'='intervals','Selected node'='node','Model diagnostics'='diagnostics','Marginal model comparison'='comparison')),
   shiny::conditionalPanel("input.bm_framework == 'Bayes'",ns=ns,shiny::selectInput(ns('bm_parameter'),'Posterior parameter',c('sig2','logLik'))),
   shiny::selectInput(ns('bm_palette'),'Palette',c('Guane','Legacy','Grayscale')),
   shiny::checkboxInput(ns('bm_labels'),'Show tip labels',TRUE),shiny::checkboxInput(ns('bm_nodes'),'Show node numbers',FALSE),
   shiny::sliderInput(ns('bm_label_size'),'Label size',min=.3,max=1.2,value=.7,step=.1),
   ui_asr_graphics(ns,'bm',continuous=TRUE),
   shiny::downloadButton(ns('bm_pdf'),'Download graph PDF'),shiny::downloadButton(ns('bm_script'),'Download graph R code'))),
  shiny::h4('Selected node'),shiny::tableOutput(ns('bm_node_detail')),shiny::downloadButton(ns('bm_node_csv'),'Download selected node CSV'),
  shiny::textOutput(ns('bm_metadata')),shiny::tableOutput(ns('bm_estimates')),
  shiny::p('Branch colors and phenogram lines interpolate node estimates; they are not conditional evolutionary trajectories.'),
  shiny::textOutput(ns('bm_uncertainty')),
  shiny::conditionalPanel("input.bm_framework == 'Bayes'",ns=ns,shiny::downloadButton(ns('bm_draws_csv'),'Download retained posterior CSV'),shiny::downloadButton(ns('bm_chains_rds'),'Download full chains and settings RDS')),
  shiny::downloadButton(ns('bm_csv'),'Download node estimates CSV')),
 diagnostics=shiny::tagList(shiny::div(class='guane-asr-figure',shiny::plotOutput(ns('bm_diagnostics'),height='auto')),
  shiny::downloadButton(ns('bm_diagnostic_pdf'),'Download graph PDF'),shiny::downloadButton(ns('bm_diagnostic_script'),'Download graph R code'),shiny::tableOutput(ns('bm_summary')),
  shiny::textOutput(ns('bm_likelihood')),
  shiny::conditionalPanel("input.bm_framework == 'Bayes'",ns=ns,shiny::p('ESS is the summed per-chain spectral estimate. Classic split-Rhat is not rank-normalized. Values above 1.01, low ESS or stuck chains flag unreliable sampling; passing diagnostics does not prove convergence.'),shiny::div(style='overflow-x:auto',shiny::tableOutput(ns('bm_chain_diagnostics'))),shiny::downloadButton(ns('bm_chain_csv'),'Download chain diagnostics CSV')),
  shiny::conditionalPanel("input.bm_framework != 'Bayes'",ns=ns,shiny::tableOutput(ns('bm_comparison')),shiny::downloadButton(ns('bm_comparison_csv'),'Download model comparison CSV'),
  shiny::p('AIC weights describe the candidate set, not certainty that a model is true. Boundary fits require caution. Failed candidates remain visible; weights are withheld if any candidate fails.'),
  shiny::p('fastAnc diagnostics show BM contrasts. Other engines show decorrelated tip residuals using the fitted covariance; these are exploratory, order-dependent checks, not a calibrated model-adequacy test.')),
  shiny::textOutput(ns('bm_warnings'))),
 mirror=shiny::verbatimTextOutput(ns('bm_code')))
}
