ui_mod_asr_poly <- function(id) {
 ns<-shiny::NS(id)
 ui_mod_analysis_base(id,'poly','Polymorphic traits',
 controls=shiny::tagList(
  shiny::selectInput(ns('poly_trait'),'Trait for reconstruction',NULL),
  shiny::selectInput(ns('poly_framework'),'Framework',c('Maximum likelihood'='ML','Stochastic mapping (fixed fitted rates)'='simmap','Bayesian Mk (sample rates)'='Bayes','Parsimony \u2014 planned'='parsimony')),
  shiny::p('Code coexisting states with +, such as A+B. Missing, ambiguous and empty states are not supported.'),
  shiny::p('Use two or three constituent states and at least one polymorphic taxon.'),
  shiny::selectInput(ns('poly_model'),'Model',c('ER','SYM','ARD','transient')),
  shiny::checkboxInput(ns('poly_ordered'),'Ordered polymorphism',FALSE),
  shiny::conditionalPanel(sprintf("input['%s']",ns('poly_ordered')),
   shiny::textAreaInput(ns('poly_order'),'Constituent order (one state per line)',rows=3),
   shiny::numericInput(ns('poly_max_poly'),'Maximum polymorphism',2,min=2,max=3,step=1),
   shiny::p('Only contiguous combinations in the specified order are allowed. Maximum polymorphism limits the number of coexisting states. No order is inferred automatically.')),
  shiny::conditionalPanel(sprintf("!input['%s']",ns('poly_ordered')),shiny::p('Unordered model: transitions add or lose one constituent state. All combinations are included, even if unobserved. Direct monomorphic substitutions are forbidden.')),
  shiny::h4('Transition preview'),shiny::textOutput(ns('poly_preview_status')),
  shiny::div(style='overflow-x:auto',shiny::tableOutput(ns('poly_preview'))),
  shiny::p('Rows are source states; columns are destinations. Zero forbids a transition; equal positive indices share a rate. This preview does not fit a model.'),
  shiny::p('ER shares allowed rates; SYM ties reverse rates; ARD separates directions; transient uses one loss rate and one gain rate.'),
  shiny::p('Root probabilities apply to combined states, not to constituent states. A+B represents coexistence, not uncertain coding.'),
  shiny::conditionalPanel(sprintf("input['%s'] != 'Bayes'",ns('poly_framework')),
  ui_asr_reconstruction(ns,'poly'),
  ui_asr_mk_advanced(ns,'poly'),
  shiny::checkboxInput(ns('poly_compare'),'Compare polymorphic models',FALSE)),
  ui_asr_bayes_controls(ns,'poly',show_index=FALSE),
  shiny::conditionalPanel(sprintf("input['%s'] == 'simmap'",ns('poly_framework')),
   shiny::numericInput(ns('poly_nsim'),'Number of histories',100,min=2,max=500,step=1),
   shiny::numericInput(ns('poly_seed'),'Mapping seed',999,min=0,max=2147483646,step=1),
   shiny::p('Histories are conditional on the fitted Q matrix, observed tips, tree and the selected root probabilities. Rates and trees are not sampled. There is no MCMC burn-in.')),
  shiny::actionButton(ns('poly_run'),'Run polymorphic reconstruction'),shiny::textOutput(ns('poly_status'))),
 results=shiny::tagList(shiny::fluidRow(
  shiny::column(9,shiny::div(class='guane-asr-figure',shiny::plotOutput(ns('poly_plot'),height='auto'))),
  shiny::column(3,shiny::h4('Graph controls'),
   shiny::selectInput(ns('poly_graph'),'Graph',c('Node probability tree'='tree','Transition-rate diagram'='rates','Marginal state probabilities'='probabilities','Model comparison'='comparison','Optimizer starts'='starts')),
   shiny::conditionalPanel(sprintf("input['%s'] == 'simmap' || input['%s'] == 'Bayes'",ns('poly_framework'),ns('poly_framework')),shiny::numericInput(ns('poly_history'),'History to display',1,min=1,step=1)),
   shiny::conditionalPanel(sprintf("input['%s'] == 'Bayes'",ns('poly_framework')),shiny::selectInput(ns('poly_bayes_parameter'),'Posterior parameter',c('q1','logLik'))),
   shiny::selectInput(ns('poly_palette'),'Palette',c('Guane','Legacy','Grayscale')),
   shiny::checkboxInput(ns('poly_labels'),'Show tip labels',TRUE),shiny::checkboxInput(ns('poly_nodes'),'Show node numbers',FALSE),
   shiny::sliderInput(ns('poly_label_size'),'Label size',min=.3,max=1.2,value=.7,step=.1),
   shiny::sliderInput(ns('poly_pie_size'),'Node pie size',min=.2,max=1.5,value=.6,step=.1),
   ui_asr_graphics(ns,'poly',continuous=FALSE),
   shiny::downloadButton(ns('poly_pdf'),'Download graph PDF'),shiny::downloadButton(ns('poly_script'),'Download graph R code'))),
  shiny::h4('Selected node'),shiny::tableOutput(ns('poly_node_detail')),shiny::downloadButton(ns('poly_node_csv'),'Download selected node CSV'),
  shiny::textOutput(ns('poly_metadata')),
  shiny::conditionalPanel(sprintf("input['%s'] == 'density'",ns('poly_graph')),shiny::downloadButton(ns('poly_density_csv'),'Download density segments CSV')),
shiny::conditionalPanel(sprintf("input['%s'] == 'simmap' || input['%s'] == 'Bayes'",ns('poly_framework'),ns('poly_framework')),
   shiny::textOutput(ns('poly_mapping_info')),
   shiny::conditionalPanel(sprintf("input['%s'] != 'Bayes'",ns('poly_framework')),shiny::p('Simulation ranges describe the central 95% of sampled histories, not confidence intervals for the mean or uncertainty in fitted rates. MCSE measures Monte Carlo precision; small samples and zero sampled events can be misleading.')),
   shiny::h4('Transition counts'),shiny::div(style='overflow-x:auto',shiny::tableOutput(ns('poly_transitions'))),
   shiny::downloadButton(ns('poly_transitions_csv'),'Download transition summary CSV'),
   shiny::h4('State occupancy'),shiny::div(style='overflow-x:auto',shiny::tableOutput(ns('poly_occupancy'))),
   shiny::downloadButton(ns('poly_occupancy_csv'),'Download state occupancy CSV'),
   shiny::downloadButton(ns('poly_frequency_csv'),'Download sampled node frequencies CSV'),
   shiny::downloadButton(ns('poly_maps_rds'),'Download histories and summaries RDS')),shiny::textOutput(ns('poly_interpretation')),
  shiny::conditionalPanel(sprintf("input['%s'] != 'Bayes'",ns('poly_framework')),shiny::p('Node pies show marginal state probabilities conditional on the fitted rates, tree and the selected root probabilities. They do not integrate parameter or tree uncertainty and are not sampled evolutionary histories.')),
  shiny::h4('Coding audit'),shiny::p('Combination order is canonicalized for fitting; original data remain unchanged.'),
  shiny::div(style='overflow-x:auto',shiny::tableOutput(ns('poly_coding'))),shiny::downloadButton(ns('poly_coding_csv'),'Download coding audit CSV'),
  shiny::conditionalPanel(sprintf("input['%s'] == 'joint' && input['%s'] != 'Bayes'",ns('poly_reconstruction'),ns('poly_framework')),shiny::h4('Joint ancestral assignments'),shiny::tableOutput(ns('poly_joint')),shiny::textOutput(ns('poly_joint_info')),shiny::downloadButton(ns('poly_joint_csv'),'Download joint assignments CSV'),
  shiny::p('Joint assignments maximize the simultaneous ancestral configuration. Ties may occur; assignments are not probabilities.')),
  ui_asr_bayes_results(ns,'poly'),
  shiny::downloadButton(ns('poly_results_rds'),'Download analysis RDS'),
  shiny::h4('Marginal state probabilities'),shiny::div(style='overflow-x:auto',shiny::tableOutput(ns('poly_probabilities'))),
  shiny::downloadButton(ns('poly_csv'),'Download node probabilities CSV'),
  shiny::h4('Selected Q matrix'),shiny::p('Rows are source states; columns are destination states. Off-diagonal rates are per branch-length unit; diagonal entries are negative row sums.'),
  shiny::div(style='overflow-x:auto',shiny::tableOutput(ns('poly_q'))),shiny::downloadButton(ns('poly_q_csv'),'Download rate matrix CSV'),
  shiny::h4('Rate constraints'),shiny::div(style='overflow-x:auto',shiny::tableOutput(ns('poly_constraints')))),
 diagnostics=shiny::tagList(
  shiny::conditionalPanel(sprintf("input['%s'] == 'simmap'",ns('poly_framework')),
   shiny::h4('Monte Carlo agreement'),shiny::div(class='guane-asr-figure',shiny::plotOutput(ns('poly_mc_plot'),height='auto')),
   shiny::downloadButton(ns('poly_mc_pdf'),'Download graph PDF'),shiny::downloadButton(ns('poly_mc_script'),'Download graph R code'),
   shiny::p('Compare sampled node frequencies with analytic marginal probabilities. Differences should decrease with more independent histories; this plot is not an MCMC convergence or model-adequacy test.'),
   shiny::div(style='overflow-x:auto',shiny::tableOutput(ns('poly_mc_table')))),

  shiny::verbatimTextOutput(ns('poly_warnings')),
  shiny::conditionalPanel(sprintf("input['%s'] != 'Bayes'",ns('poly_framework')),
  shiny::p('Starting values and effective calls are recorded per model. Convergence does not establish identifiability or model adequacy. Near-boundary rates and different optima require caution.'),
  shiny::h4('Model comparison'),shiny::div(class='guane-asr-figure',shiny::plotOutput(ns('poly_diagnostics'),height='auto')),
  shiny::downloadButton(ns('poly_diagnostic_pdf'),'Download graph PDF'),shiny::downloadButton(ns('poly_diagnostic_script'),'Download graph R code'),
  shiny::div(style='overflow-x:auto',shiny::tableOutput(ns('poly_comparison'))),
  shiny::p('Comparisons use the same taxa, complete state space and the selected root probabilities. AIC weights cover converged candidates only; no model averaging is performed.'),
  shiny::downloadButton(ns('poly_comparison_csv'),'Download model comparison CSV'),
  shiny::h4('Optimizer starts'),shiny::div(style='overflow-x:auto',shiny::tableOutput(ns('poly_attempts'))),shiny::downloadButton(ns('poly_attempts_csv'),'Download optimizer diagnostics CSV'),
  shiny::p('Select Model comparison or Optimizer starts in Graph controls to view and export diagnostic plots.')),
  ui_asr_bayes_diagnostics(ns,'poly')),

 mirror=shiny::verbatimTextOutput(ns('poly_code')))
}
