ui_mod_div_rates <- function(id) {
 ns<-shiny::NS(id)
 ui_mod_analysis_base(id,'rates','Constant-rate models',
 controls=shiny::tagList(
shiny::tags$details(open=TRUE,shiny::tags$summary('Model and data settings'),
  shiny::p('Uses the tree from Data; a trait table is not required.'),
  shiny::checkboxGroupInput(ns('rates_models'),'Models',c('Yule (mu = 0)'='Yule','Birth-death'='BD'),selected=c('Yule','BD')),
  shiny::numericInput(ns('rates_sampling'),'Random extant sampling fraction',1,min=.000001,max=1,step=.01),
  shiny::checkboxInput(ns('rates_survival'),'Condition on crown survival and root split',TRUE),
  shiny::p('Sampling assumes independent random inclusion of extant species. Nonrandom or diversified sampling is not modeled.'),
  shiny::p('Crown-tree likelihood; supplied stems are excluded. No tip-number conditioning. Both models use the same sampling and conditioning settings.')),
shiny::tags$details(shiny::tags$summary('Advanced fitting controls'),
  shiny::selectInput(ns('rates_optimizer'),'Optimizer',c('nlminb','L-BFGS-B')),
  shiny::numericInput(ns('rates_maxit'),'Maximum iterations',2000,min=10,max=20000,step=100),
  shiny::textInput(ns('rates_upper'),'Rate upper bound (blank = 100 / crown age)',''),
  shiny::textInput(ns('rates_start_lambda'),'Initial lambda (blank = derived)',''),
  shiny::textInput(ns('rates_start_mu'),'Initial mu (blank = lambda / 2)',''),
  shiny::p('Several deterministic starts are tried. Extinction may exceed speciation; no positive net-diversification constraint is imposed.'),
  shiny::checkboxInput(ns('rates_intervals'),'Calculate approximate curvature intervals',TRUE),
  shiny::checkboxInput(ns('rates_slices'),'Save likelihood slices',TRUE)),
  shiny::actionButton(ns('rates_run'),'Run diversification models'),shiny::textOutput(ns('rates_status')),
shiny::tags$details(shiny::tags$summary('Uncertainty and diagnostics'),
  shiny::checkboxInput(ns('rates_profiles'),'Calculate profile likelihoods',TRUE),
  shiny::numericInput(ns('rates_level'),'Profile reference level',.95,min=.8,max=.99,step=.01),
  shiny::numericInput(ns('rates_points'),'Profile grid points',61,min=21,max=201,step=20),
  shiny::checkboxInput(ns('rates_simulate'),'Simulate conditional LTT curves',TRUE),
  shiny::numericInput(ns('rates_nsim'),'Simulation replicates',200,min=20,max=2000,step=100),
  shiny::numericInput(ns('rates_simseed'),'Simulation seed',999,min=0,max=2147483647,step=1),
  shiny::actionButton(ns('rates_diagnose'),'Run uncertainty and diagnostics'),
  shiny::p('Run models first. Diagnostic settings clear only diagnostics; rerun diagnostics after changing them.'))),
 results=shiny::tagList(shiny::fluidRow(
  shiny::column(9,shiny::div(class='guane-asr-figure',shiny::plotOutput(ns('rates_plot'),height='auto'))),
  shiny::column(3,shiny::h4('Graph controls'),
shiny::selectInput(ns('rates_graph'),'Graph',c('Rate estimates'='rates','Model comparison'='comparison','Likelihood slice'='slice','Profile likelihood'='profile','Conditional LTT check'='adequacy','Conditional discrepancy reference'='discrepancy')),
   shiny::selectInput(ns('rates_plot_model'),'Model',c('Yule','BD')),
   shiny::selectInput(ns('rates_parameter'),'Parameter',c('lambda','mu','net')),
   shiny::selectInput(ns('rates_palette'),'Palette',c('Guane','Legacy','Grayscale')),
   shiny::downloadButton(ns('rates_pdf'),'Download graph PDF'),shiny::downloadButton(ns('rates_png'),'Download graph PNG'),shiny::downloadButton(ns('rates_script'),'Download graph R code'))),
  shiny::textOutput(ns('rates_metadata')),
  shiny::p('lambda is speciation, mu is extinction, and net is lambda minus mu. Rates are per branch-length unit, not automatically per million years.'),
  shiny::tableOutput(ns('rates_estimates')),shiny::downloadButton(ns('rates_csv'),'Download estimates CSV'),
  shiny::p('Intervals are approximate 95% normal intervals from likelihood curvature. NA means unavailable, including fixed rates, boundary estimates, unstable curvature or negative rate limits. They exclude uncertainty in sampling fraction and tree.'),
  shiny::textOutput(ns('rates_interpretation')),shiny::tableOutput(ns('rates_comparison')),shiny::downloadButton(ns('rates_comparison_csv'),'Download model comparison CSV'),
  shiny::p('AIC weights compare only the selected models on the same likelihood basis. Weights are withheld if a candidate fails. Boundary fits and extinction estimates need caution; no likelihood-ratio p-value is reported.'),
shiny::downloadButton(ns('rates_rds'),'Download graph settings and result RDS')),
 diagnostics=shiny::tagList(
shiny::verbatimTextOutput(ns('rates_warnings')),
  shiny::h4('Profile uncertainty'),
  shiny::p('Profiles reoptimize the nuisance rate within the fitted bounds. The chi-square reference is approximate; coverage at boundaries is not calibrated. Search limits are not infinite confidence limits. Nuisance_bound flags dependence on the upper rate bound.'),
  shiny::tableOutput(ns('rates_profile_table')),
  shiny::downloadButton(ns('rates_profile_csv'),'Download profile intervals CSV'),
  shiny::downloadButton(ns('rates_profile_curves_csv'),'Download profile curves CSV'),
  shiny::h4('Conditional simulation check'),
  shiny::p('Simulations fix fitted rates, random sampling fraction, crown age and sampled tip count. They test branching-time shape, not tree size or age. The 95% envelope is pointwise, not simultaneous, and excludes parameter and tree uncertainty.'),
  shiny::p('The reference tail fraction compares a branching-time CDF discrepancy with simulations at fitted rates. It is descriptive, not a calibrated p-value; rates are not refitted per replicate. Select a diagnostic graph in Results to view and export it.'),
  shiny::tableOutput(ns('rates_adequacy_table')),
  shiny::downloadButton(ns('rates_envelope_csv'),'Download simulation envelope CSV'),
  shiny::downloadButton(ns('rates_draws_csv'),'Download simulated branching times CSV'),

  shiny::p('Likelihood slices hold the other rate fixed. They reveal local curvature but are not profile likelihoods or confidence intervals. Select Likelihood slice in Graph controls to view and export them.'),
  shiny::downloadButton(ns('rates_slices_csv'),'Download likelihood slices CSV'),
  shiny::tableOutput(ns('rates_attempts')),shiny::downloadButton(ns('rates_attempts_csv'),'Download optimizer diagnostics CSV')),
 mirror=shiny::verbatimTextOutput(ns('rates_code')))
}
