ui_mod_signal_PGLM <- function(id) {
 ns<-shiny::NS(id)
 ui_mod_analysis_base(id,'PGLM','PGLM',
 controls=shiny::tagList(shiny::h4('Phylogenetic generalized linear models'),
  shiny::selectInput(ns('pglm_family'),'Response family',c('Binary (Bernoulli / logit)'='binary','Counts (Poisson GEE / log)'='count','Grouped binomial (GEE / logit)'='grouped')),
  shiny::uiOutput(ns('pglm_guidance')),
  shiny::selectInput(ns('pglm_response'),'Response / successes',NULL),
  shiny::conditionalPanel("input.pglm_family == 'grouped'",ns=ns,shiny::selectInput(ns('pglm_trials'),'Total trials',NULL)),
  shiny::conditionalPanel("input.pglm_family == 'binary'",ns=ns,shiny::selectInput(ns('pglm_event'),'Event state (1)',NULL)),
  shiny::selectInput(ns('pglm_predictors'),'Predictors',NULL,multiple=TRUE),
  shiny::selectInput(ns('pglm_categorical'),'Categorical predictors',NULL,multiple=TRUE),
  shiny::uiOutput(ns('pglm_references')),
  shiny::p('Mark categorical predictors explicitly, including numeric state codes. Other predictors are continuous.'),
  shiny::conditionalPanel("input.pglm_family == 'binary'",ns=ns,shiny::selectInput(ns('pglm_method'),'Estimation method',c('logistic_MPLE','logistic_IG10'))),
  shiny::actionButton(ns('pglm_run'),'Run PGLM'),
  shiny::actionButton(ns('pglm_influence_run'),'Run taxon influence diagnostics'),
  shiny::p('Refits the current model once per taxon on temporary pruned copies. Prepared data stay unchanged. Large datasets may take time.'),shiny::textOutput(ns('pglm_status')),
  shiny::p('Bayesian models are planned.')),
 results=shiny::tagList(shiny::fluidRow(
  shiny::column(9,shiny::plotOutput(ns('pglm_plot'),height='480px')),
  shiny::column(3,shiny::h4('Graph controls'),
   shiny::selectInput(ns('pglm_graph'),'Graph',c('Observed and fitted values'='fit','Coefficient intervals'='coefficients','Pearson residual'='diagnostics')),
   shiny::selectInput(ns('pglm_color'),'Palette',c('Guane'='#34765b','Guane legacy'='#02b2ce','Grayscale'='#444444')),
   shiny::checkboxInput(ns('pglm_labels'),'Show tip labels',FALSE),
   shiny::downloadButton(ns('pglm_pdf'),'Download graph PDF'),shiny::downloadButton(ns('pglm_script'),'Download graph R code'))),
  shiny::verbatimTextOutput(ns('pglm_metadata')),shiny::tableOutput(ns('pglm_coefficients')),shiny::tableOutput(ns('pglm_coding')),
  shiny::p('Category coefficients compare each state with its reference, holding other predictors constant.'),
  shiny::uiOutput(ns('pglm_interpretation')),
  shiny::downloadButton(ns('pglm_csv'),'Download coefficients CSV'),shiny::downloadButton(ns('pglm_predictions'),'Download fitted values CSV')),
 diagnostics=shiny::tagList(shiny::plotOutput(ns('pglm_diagnostics'),height='400px'),
  shiny::uiOutput(ns('pglm_diagnostic_help')),shiny::tableOutput(ns('pglm_count_diagnostics')),
  shiny::h4('Diagnostic screens'),shiny::p('LargeResidual marks absolute Pearson residuals above 2; Sparse marks fewer than 3 taxa. OneOutcome marks a category with only successes or failures. These are descriptive screens, not tests or automatic exclusions; absence of flags does not rule out separation.'),
  shiny::tableOutput(ns('pglm_taxa_screen')),shiny::tableOutput(ns('pglm_category_screen')),
  shiny::h4('Taxon influence'),shiny::plotOutput(ns('pglm_influence_plot'),height='350px'),shiny::tableOutput(ns('pglm_influence_table')),
  shiny::p('Influence is the largest absolute coefficient change divided by its full-fit standard error. Inspect failed refits and warnings. This is sensitivity analysis, not a calibrated test or cross-validation.'),
  shiny::downloadButton(ns('pglm_influence_csv'),'Download influence CSV'),shiny::downloadButton(ns('pglm_influence_pdf'),'Download influence PDF'),shiny::downloadButton(ns('pglm_influence_script'),'Download influence R code'),
  shiny::textOutput(ns('pglm_warnings')),shiny::tags$details(shiny::tags$summary('Model details'),shiny::verbatimTextOutput(ns('pglm_details')))),
 mirror=shiny::tagList(shiny::p('The script embeds prepared data and settings and reproduces the selected graph in RStudio.'),shiny::verbatimTextOutput(ns('pglm_code')),shiny::verbatimTextOutput(ns('pglm_influence_code'))))
}
