ui_mod_signal_PagelReg <- function(id) {
 ns<-shiny::NS(id)
 ui_mod_analysis_base(id,'PagelReg',"Pagel's correlation",
 controls=shiny::tagList(shiny::h4("Pagel's 1994 Discrete Correlation Test"),
  shiny::textOutput(ns('pagel_readiness')),
  shiny::selectInput(ns('pagel_x'),'Binary trait X',NULL),shiny::selectInput(ns('pagel_y'),'Binary trait Y',NULL),
  shiny::numericInput(ns('pagel_starts'),'Optimization starts',3,min=1,max=5,step=1),
  shiny::numericInput(ns('pagel_max'),'Maximum rate per branch-length unit',100,min=.001),
  shiny::p('ARD models: four independent rates versus eight dependent rates. Equal root probabilities for all four joint states.'),
  shiny::actionButton(ns('pagel_run'),"Run Pagel's correlation"),shiny::textOutput(ns('pagel_status'))),
 results=shiny::tagList(shiny::fluidRow(shiny::column(9,shiny::plotOutput(ns('pagel_plot'),height='500px')),
  shiny::column(3,shiny::h4('Graph controls'),
   shiny::selectInput(ns('pagel_graph'),'Evolution model',c('Dependent evolution'='dependent','Independent evolution'='independent')),
   shiny::selectInput(ns('pagel_palette'),'Palette',c('Guane','Grayscale')),
   shiny::checkboxInput(ns('pagel_width'),'Scale arrows by rate',TRUE),
   shiny::downloadButton(ns('pagel_pdf'),'Download graph PDF'),shiny::downloadButton(ns('pagel_script'),'Download graph R code'))),
  shiny::h4('Binary state mapping'),shiny::tableOutput(ns('pagel_mapping')),
  shiny::tags$details(shiny::tags$summary('Transition rates'),shiny::tableOutput(ns('pagel_rates'))),
  shiny::h4('Model comparison'),shiny::tableOutput(ns('pagel_comparison')),
  shiny::h4('Likelihood-ratio test'),shiny::tableOutput(ns('pagel_test')),
  shiny::p('A small asymptotic p-value supports dependent evolution under these models; it does not establish causation or a direction of influence.'),
  shiny::p('Compare AIC only for models fitted to the same data and root assumptions. Zero-rate boundaries and sparse states can undermine the chi-squared approximation.'),
  shiny::downloadButton(ns('pagel_csv'),'Download transition rates CSV'),shiny::downloadButton(ns('pagel_summary_csv'),'Download model comparison CSV')),
 diagnostics=shiny::tagList(shiny::h4('Joint state counts'),shiny::tableOutput(ns('pagel_counts')),
  shiny::uiOutput(ns('pagel_warnings')),shiny::h4('Optimization attempts'),shiny::tableOutput(ns('pagel_attempts')),
  shiny::p('Convergence code 0 is required. Each model retains its highest converged likelihood across the requested starts.'),
  shiny::p('Rates have no uncertainty intervals in this version. Parametric bootstrap and directional models are not implemented.')),
 mirror=shiny::tagList(shiny::p('The script embeds prepared binary inputs, refits both models and reproduces the selected diagram in RStudio.'),shiny::verbatimTextOutput(ns('pagel_code'))))
}
