ui_mod_sse_quasse <- function(id) {
 ns<-shiny::NS(id)
 ui_mod_analysis_base(id,'quasse','QuaSSE',controls=shiny::tagList(
  shiny::tags$details(open=TRUE,shiny::tags$summary('Model and data settings'),
   shiny::selectInput(ns('quasse_trait'),'Continuous trait',choices=NULL),
   shiny::selectInput(ns('quasse_error_column'),'Measurement-error column',choices=c('Common standard error'='')),
   shiny::numericInput(ns('quasse_error'),'Common measurement standard error',1,min=.000001),
   shiny::p('Supply standard errors of trait means in trait units. The common value is used only when no error column is selected; zero and missing errors are unsupported.'),
   shiny::selectInput(ns('quasse_lambda'),'Speciation function',c('Constant','Exponential','Sigmoid')),
   shiny::selectInput(ns('quasse_mu'),'Extinction function',c('Constant','Exponential','Sigmoid')),
   shiny::checkboxInput(ns('quasse_baseline'),'Compare with constant rates',TRUE),
   shiny::p('Constant: c. Exponential: base * exp(slope * x). Sigmoid: y0 + (y1-y0) * plogis(r * (x-xmid)). Drift is fixed at zero by default; edit Fixed to estimate it.'),
   shiny::numericInput(ns('quasse_sampling'),'Sampling fraction',1,min=.001,max=1,step=.05),
   shiny::checkboxInput(ns('quasse_survival'),'Condition on crown survival and root split',TRUE),
   shiny::selectInput(ns('quasse_root'),'Root treatment',c('Observed (ROOT.OBS)'='OBS','Flat (ROOT.FLAT)'='FLAT','Normal density (ROOT.GIVEN)'='GIVEN')),
   shiny::numericInput(ns('quasse_root_mean'),'Given root mean',0),shiny::numericInput(ns('quasse_root_sd'),'Given root standard deviation',1,min=.000001),
   shiny::p('Given root settings apply only to ROOT.GIVEN. ROOT.OBS is likelihood-based; ROOT.FLAT is uniform on the numerical domain. Root settings are shared across candidates.')),
  shiny::tags$details(shiny::tags$summary('Advanced fitting controls'),
   shiny::checkboxInput(ns('quasse_verify'),'Verify with an independent optimizer',TRUE),
   shiny::actionButton(ns('quasse_fill'),'Fill parameter table'),shiny::textAreaInput(ns('quasse_parameters'),'QuaSSE parameter table (CSV)','',rows=10),
   shiny::p('Columns: Parameter,Group,Fixed,Start,Lower,Upper. Equal groups tie parameters; numeric Fixed fixes the group. Signed slopes, midpoints and drift are allowed; diffusion must be positive. Clear the table after changing rate functions.'),
   shiny::selectInput(ns('quasse_optimizer'),'Optimizer',c('nlminb','L-BFGS-B')),shiny::numericInput(ns('quasse_starts'),'Optimizer starts',2,min=1,max=8),shiny::numericInput(ns('quasse_maxit'),'Maximum iterations',200,min=10,max=5000),
   shiny::checkboxInput(ns('quasse_slices'),'Save likelihood slices',FALSE)),
  shiny::tags$details(shiny::tags$summary('Numerical integration controls'),
   shiny::selectInput(ns('quasse_method'),'FFT backend',c('fftC','fftR')),
   shiny::selectInput(ns('quasse_nx'),'Trait grid bins',c(128,256,512,1024,2048,4096),selected=1024),
   shiny::selectInput(ns('quasse_r'),'Tip resolution multiplier',c(1,2,4,8),selected=4),
   shiny::numericInput(ns('quasse_step'),'Maximum time step / tree depth',.001,min=.00001,max=.05),
   shiny::numericInput(ns('quasse_tc'),'Resolution switch / tree depth',.1,min=.001,max=.999),
   shiny::numericInput(ns('quasse_range'),'Trait range multiplier',5,min=3,max=30),
   shiny::numericInput(ns('quasse_xmid'),'Grid midpoint (blank = observed midpoint)',NA),
   shiny::numericInput(ns('quasse_w'),'Convolution width (standard deviations)',5,min=3,max=10),
   shiny::checkboxInput(ns('quasse_tips'),'Integrate tips together (fftC only)',FALSE),
   shiny::p('Every fit is checked with twice the grid bins and half the time step. Unstable likelihoods suppress model weights. Increase resolution and refit when diagnostics fail.')),
  shiny::tags$details(shiny::tags$summary('Robustness refits'),shiny::numericInput(ns('quasse_domain_factor'),'Domain widening factor',1.5,min=1.01,max=2),shiny::actionButton(ns('quasse_robust_run'),'Run grid and domain refits')),
  shiny::actionButton(ns('quasse_run'),'Run QuaSSE'),shiny::textOutput(ns('quasse_status'))),
 results=shiny::tagList(
  shiny::fluidRow(shiny::column(9,shiny::div(class='guane-asr-figure',shiny::plotOutput(ns('quasse_plot'),height='auto'))),shiny::column(3,
   shiny::h4('Graph controls'),shiny::selectInput(ns('quasse_graph'),'Graph',c('Rates versus trait'='rates','Observed tip states'='tree','Traits and measurement errors'='observations','Model comparison'='comparison','Optimizer starts'='starts','Independent optimizer verification'='verification','Likelihood slice'='slice','Grid and domain refits'='robustness')),
   shiny::selectInput(ns('quasse_plot_model'),'Model',choices='Selected'),shiny::selectInput(ns('quasse_plot_parameter'),'Parameter',choices=NULL),
   shiny::selectInput(ns('quasse_palette'),'Palette',c('Guane','Legacy','Grayscale')),shiny::checkboxInput(ns('quasse_labels'),'Show tip labels',TRUE),
   shiny::numericInput(ns('quasse_font'),'Label size',.7,min=.2,max=2),shiny::numericInput(ns('quasse_width'),'Figure width (inches)',10,min=5,max=24),shiny::numericInput(ns('quasse_height'),'Figure height (inches)',7,min=4,max=24),
   shiny::downloadButton(ns('quasse_pdf'),'Download graph PDF'),shiny::downloadButton(ns('quasse_png'),'Download graph PNG'),shiny::downloadButton(ns('quasse_script'),'Download graph R code'))),
  shiny::textOutput(ns('quasse_metadata')),shiny::tableOutput(ns('quasse_estimates')),shiny::downloadButton(ns('quasse_csv'),'Download estimates CSV'),
  shiny::tableOutput(ns('quasse_comparison')),shiny::downloadButton(ns('quasse_comparison_csv'),'Download model comparison CSV'),
  shiny::p('Rates use branch-length units; drift uses trait units per branch-length unit and diffusion uses squared trait units per branch-length unit. Curves cover the observed trait range only.'),
  shiny::textOutput(ns('quasse_interpretation')),shiny::downloadButton(ns('quasse_rds'),'Download graph settings and result RDS')),
 diagnostics=shiny::tagList(shiny::tableOutput(ns('quasse_robustness')),shiny::downloadButton(ns('quasse_robust_csv'),'Download robustness CSV'),shiny::verbatimTextOutput(ns('quasse_warnings')),shiny::tableOutput(ns('quasse_diagnostics')),shiny::tableOutput(ns('quasse_attempts')),
  shiny::downloadButton(ns('quasse_attempts_csv'),'Download optimizer diagnostics CSV'),shiny::downloadButton(ns('quasse_slices_csv'),'Download likelihood slices CSV'),
  shiny::h4('Effective parameter constraints'),shiny::tableOutput(ns('quasse_constraints')),
  shiny::p('Likelihood slices hold other free rates fixed and respect tied parameters. They are not confidence intervals or nuisance-refitted profiles.')),
 mirror=shiny::verbatimTextOutput(ns('quasse_code')))
}
